### ISSUE TITLE
希望能支持自定义编辑时字段的样式

### ISSUE THREAD

**Issue by zwgshr** [huangshuwei/vue-easytable#10]
功能类似于 `formatter: function (rowData,rowIndex,pagingIndex,field)`
方便编辑日期、下拉等字段

**Comment by huangshuwei** [comment]
感谢提醒，现在只能编辑纯文本，按照你的方式就可以对编辑后的结果进行二次加工了。👍

**Comment by huangshuwei** [comment]
已发布
https://github.com/huangshuwei/vue-easytable/releases/tag/1.2.2

具体实例参考
http://localhost:8098/examples/app.html#/table?anchor=table-cell-edit-advanced
