### ISSUE TITLE
表头最后一列的横向边线距离右边框有 1px 的间隙

### ISSUE THREAD

**Issue by varzy** [huangshuwei/vue-easytable#100]
作者您好，

我在使用 vue-easytable 时，发现表头最后一列的横向边线距离右边框有 1px 的间隙。本来以为是我代码的问题，后来发现官方 demo 上也存在这一现象。由于我需要给表头加背景色，且我的项目要在手机端使用，屏幕尺寸一小这个小小的间隙就变得十分明显。

我的项目：

![snipaste_2018-01-26_16-04-49](https://user-images.githubusercontent.com/13913491/35430354-dfbd8c46-02b2-11e8-96f2-1f129757b44e.png)

官方 demo：

![snipaste_2018-01-26_16-05-27](https://user-images.githubusercontent.com/13913491/35430362-e5bb72b6-02b2-11e8-8f66-12a0e06d64f8.png)

目前我只能强制修改此 class，改为 'right: -2px' 以解决此问题

![3](https://user-images.githubusercontent.com/13913491/35430428-29f84a6c-02b3-11e8-955c-ec787cd289ea.png)

**Comment by huangshuwei** [comment]
收到，感谢反馈

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
