### ISSUE TITLE
当从第一行合并的时候，单元格没有宽度

### ISSUE THREAD

**Issue by snowmei** [huangshuwei/vue-easytable#103]
![image](https://user-images.githubusercontent.com/26371460/35498721-6a87070e-050a-11e8-920f-e912d775eedd.png)

**Comment by huangshuwei** [comment]
我测了下好像没问题，实例：
https://jsfiddle.net/kd2vxpe5/

或许我们的配置不同，你可以给我提供一个jsfiddle 实例我看下

**Comment by snowmei** [comment]
之前我是把你的代码下载下来了，可能改了一部分东西影响了，刚才测试了一下没问题了
