### ISSUE TITLE
侧菜单关闭，不能自适应

### ISSUE THREAD

**Issue by corasql** [huangshuwei/vue-easytable#104]
![image](https://user-images.githubusercontent.com/5822957/35514628-c5123540-0541-11e8-95d1-c608ab75f355.png)

当关闭左侧时会出现以下问题
![image](https://user-images.githubusercontent.com/5822957/35514532-712e477a-0541-11e8-89af-73890e13db8c.png

**Comment by huangshuwei** [comment]
重复 #78

**Comment by corasql** [comment]
用resize可以解决，但需动手动啊

**Comment by huangshuwei** [comment]
明白，想到好的方案会修复的

**Comment by zongpengz** [comment]
表示遇到类似的问题。当很多页面都有表格时， 用resize方法很烦啊。希望尽快修复啊 @huangshuwei

**Comment by corasql** [comment]
修复这个问题了吗

**Comment by LookForwardPersistence** [comment]
遇到同样的问题

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
