### ISSUE TITLE
demo例子表头显示异常

### ISSUE THREAD

**Issue by 359257840** [huangshuwei/vue-easytable#106]
![image](https://user-images.githubusercontent.com/11308580/35657518-d207bc28-0737-11e8-973f-14e937f44a75.png)
使用的一下例子代码
![image](https://user-images.githubusercontent.com/11308580/35657533-eaafa632-0737-11e8-9e06-63c0f5504840.png)
程序里面引入组件代码

**Comment by huangshuwei** [comment]
我在 jsFiddle 上试了没问题
https://jsfiddle.net/zfevgzyn/

确认下是否有样式干扰

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
