### ISSUE TITLE
表格自适应问题

### ISSUE THREAD

**Issue by Zzeo** [huangshuwei/vue-easytable#110]
项目是用视图是写在<keep-alive><keep-alive>中的。打开多个有表格视图的页签打开过后。刷新或者调整浏览器宽度过后，就会出现以下情况：
![image](https://user-images.githubusercontent.com/26971142/36189541-0c636272-118e-11e8-8699-dee6fb5319e0.png)

**Comment by Zzeo** [comment]
刷新或者调整浏览器宽度之前， 是能够自适应撑满整个div的

**Comment by mistyrain98** [comment]
<v-table ref="easyTable" …… ></v-table>
activated () {
      this.$refs.easyTable.resize()
    }

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
