### ISSUE TITLE
行内样式问题

### ISSUE THREAD

**Issue by Zzeo** [huangshuwei/vue-easytable#113]
![image](https://user-images.githubusercontent.com/26971142/36587192-5b62ff76-18bf-11e8-8664-c18050b224a4.png)

如上图，通过配置写的一些样式难以修改。
列如：在表格的的一行内，我想要居中对齐的字体为红色，居左的为蓝色。 能写成类名控制样式吗？而不是直接把样式写在行内。
![image](https://user-images.githubusercontent.com/26971142/36587263-9b467ef6-18bf-11e8-8dca-1d12ab256874.png)

**Comment by huangshuwei** [comment]
可以通过设置单元格样式实现，具体可参考 http://doc.huangsw.com/vue-easytable/app.html#/table/cellStyle

当然table组件内部行内样式，后面我也优化下，改为 `class` 的形式
