### ISSUE TITLE
菜鸟请请教 如何下载成项目中能用的js，css文件

### ISSUE THREAD

**Issue by lxgyxp** [huangshuwei/vue-easytable#115]
刚开始学Java时间不多， 不清楚怎么使用，项目中都是类似vue-easytable.js 这种方式加载的文件，请问怎么下载到？

**Comment by lxgyxp** [comment]
好吧 好像umd目录下面的就是。。。

**Comment by huangshuwei** [comment]
是否已解决

**Comment by ly525** [comment]
@lxgyxp  [docs - installation](http://doc.huangsw.com/vue-easytable/app.html#/install)
