### ISSUE TITLE
页面同时有多个表格，其中一个表格分页时，其他表格宽度有问题

### ISSUE THREAD

**Issue by focusLee** [huangshuwei/vue-easytable#117]

**Comment by focusLee** [comment]
![image](https://user-images.githubusercontent.com/14796960/36779799-205ebab4-1cac-11e8-978d-cab775222eb9.png)

**Comment by focusLee** [comment]
分页切换时，下面表格宽度被改了。建议能不能传入一个wrapperid

**Comment by huangshuwei** [comment]
收到，我空了看下

**Comment by huangshuwei** [comment]
我写了一个实例，但是没有重现
https://jsfiddle.net/eavtvob7/3/

希望能给我提供一个实例

**Comment by ly525** [comment]
closed because we can't reproduce the bug.
