### ISSUE TITLE
Need custom data like links and images as well in fields

### ISSUE THREAD

**Issue by ian-pinto-vamaship** [huangshuwei/vue-easytable#119]
Need custom data like links and images as well in fields

**Comment by huangshuwei** [comment]
you can look at this demo:
http://doc.huangsw.com/vue-easytable/app.html#/table/customColumns

**Comment by ian-pinto-vamaship** [comment]
thanks huangshuwei for the prompt response, formatter function did the trick.
For instance in my Logistics vue based app I used 
```
formatter: function (rowData, index, pagingIndex) {
                return rowData.service === 'ocean' ? '<i class="fa fa-ship" />' : '<i class="fa fa-fighter-jet" />'
              }
```
to conditionally display a ship or plane icon for a specific service type (ocean/air)
