### ISSUE TITLE
English documentation

### ISSUE THREAD

**Issue by sdvinfo** [huangshuwei/vue-easytable#12]
Hi! 
Your table is awesome, but could you add an english documentation? ;-)

**Comment by huangshuwei** [comment]
Thanks for your support. I'll finish it as soon as possible

**Comment by rendyfebry** [comment]
Hi,, if there is any english documentation, that gonna be useful. Even not completed one gonna be great.

**Comment by ly525** [comment]
Some words in the code also need to be rewrite with i18n, I hope I can help translate the document.  And the label of issue can add english version.

**Comment by kevinding0218** [comment]
Awesome table as well!!! Really hope if there is an English language version or figuring out a way to translate label in English!

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
