### ISSUE TITLE
customize column-width-drag to auto resize to content width on click

### ISSUE THREAD

**Issue by ian-pinto-vamaship** [huangshuwei/vue-easytable#121]
Is it possible to customize column-width-drag to auto resize to content width on clicking on any column. A reference can be seen in the gif on this link: https://dribbble.com/shots/1903644-Data-Grid/attachments/325113

**Comment by ly525** [comment]
Sorry, there is no plan for this temporarily. But the reference looks great , thank you for providing the example.
