### ISSUE TITLE
能否开启自动换行，当前行的高度自适应增加？

### ISSUE THREAD

**Issue by doingdo** [huangshuwei/vue-easytable#122]
当某个单元格内容较多时，不做文本缩略，而是自动换行，并且自适应整行表格的行高，能实现吗？

**Comment by Apple-Flavor** [comment]
同求，一个td内容过多时，不能控制换行.

**Comment by Davisjy** [comment]
同求

**Comment by liqi600** [comment]
恳请支持下

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
