### ISSUE TITLE
复杂表头，通过动态配置来隐藏列信息时，出现表格数据查看不到的现象

### ISSUE THREAD

**Issue by zhanglin00129** [huangshuwei/vue-easytable#123]
![image](https://user-images.githubusercontent.com/9368209/37043170-f69687b8-219a-11e8-8983-d9ecd235b833.png)
如图所示表格，我通过勾选达到隐藏联系方式，爱好及地址，身高的功能。
通过你在其他issue里建议的通过动态配置columns来达到这个目的。

![image](https://user-images.githubusercontent.com/9368209/37043415-8960aefc-219b-11e8-8d75-c93f603c5a01.png)
可是当我把上图中的“联系方式”和“爱好及地址”去掉后，表格如上图所示，看不到表格数据了。我看了一下，数据其实是在的，只是表格body的高度是2px所以看不到了。
![image](https://user-images.githubusercontent.com/9368209/37043544-d44f9f54-219b-11e8-8d63-ee7c00e232e4.png)

jsfiddle地址：
https://jsfiddle.net/lin_zhang/eme541s7/35/

**Comment by huangshuwei** [comment]
收到，正在看

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
