### ISSUE TITLE
多次改变分辨率时,表格出现留白

### ISSUE THREAD

**Issue by alokjx** [huangshuwei/vue-easytable#125]
isResize | 此列是否要自适应，前提是设置了is-horizontal-resize:true
每列都设置了isResize    也设置了is-horizontal-resize:true,同样出现留白
![d4mg pk 5aaad78a8q8ywkp](https://user-images.githubusercontent.com/28668506/37198728-3f07df76-23ba-11e8-9546-e09123c2bd32.png)

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
