### ISSUE TITLE
能否提供行选中的背景颜色(多选模式)、列能否固定在末尾

### ISSUE THREAD

**Issue by ruiyong-lee** [huangshuwei/vue-easytable#134]
你好，能否提供表格行选中的背景颜色(多选模式)、还有isFrozen，列现在只能固定在开头，能否固定在末尾？

**Comment by ruiyong-lee** [comment]
漏看了，我提的第一个应该可以通过column-cell-class-name实现，第二个好像没找到

**Comment by ruiyong-lee** [comment]
还有列宽拖动的时候能否提供回调？

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
