### ISSUE TITLE
复杂表头遇到固定列。会发生渲染错行。

### ISSUE THREAD

**Issue by namehu** [huangshuwei/vue-easytable#136]
我的报表有复杂表头。但是在子级表头中有一列是固定的。导致渲染出现问题。如图
![snipaste_20180329_165602](https://user-images.githubusercontent.com/26371978/38079717-31ec8dec-3372-11e8-80fe-6ded94a7669d.png)
下面这个是指固定一列的情况。是好的。
![1](https://user-images.githubusercontent.com/26371978/38079818-6b11f7f6-3372-11e8-98c9-57e892733240.png)
麻烦确认下。试了好多方法。并不能绕过。

**Comment by huangshuwei** [comment]
把表格的配置信息发出来看下，在 jsfiddle 中有实例最好。

**Comment by namehu** [comment]
jsfiddle打不开，用的jsrun。这个是地址：
http://jsrun.net/WvZKp/detail

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
