### ISSUE TITLE
增加footer汇总后，表格拖动不了

### ISSUE THREAD

**Issue by scout927** [huangshuwei/vue-easytable#137]
增加了footer汇总后，当表格宽度超出屏幕宽度后不能横向拖动，删除footer后就能拖动了，请问这个该如何破

**Comment by ly525** [comment]
麻烦提供能够复现的例子，比如 codepen 或者 jsfiddle。
Please provide a reproduction link, like codepen or jsfiddle

**Comment by guowangsheng** [comment]
我也遇到了，增加footer汇总后，横向滚动条不见了，删除后正常

**Comment by guowangsheng** [comment]
刚才又试了下，固定一列的时候，滚动条可以出来了，同时又发现个问题，如果上面的列是动态的，下面的footer就会出错。Cannot read property 'width' of undefined at table-footer-mixin.js:99

**Comment by supervons** [comment]
同样遇到这个问题。。。😂

**Comment by yuyuypjk** [comment]
这个场景基本上100% 能重现了，固定头和列 添加footer汇总 这三个功能 就不能滑动内容， 同样的 设置在element 上就可以实现，建议参考

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
