### ISSUE TITLE
固定表头和首列时，往右滑动会出现表头和下面数据滑动不一致，表头有些卡顿

### ISSUE THREAD

**Issue by zzz531003529** [huangshuwei/vue-easytable#139]
当固定表头和首列时且右边有滚动条时，往右边滑动手机端明显感觉表头有卡顿现象，和数据体联动滑动的速度不一致。能问下这个表头和数据的滑动是怎么实现联动的。

**Comment by huangshuwei** [comment]
可否提供一个可访问的实例，我看下具体的问题

**Comment by ly525** [comment]
没有提供可复现的例子，已经关闭。

**Comment by benbenyao** [comment]
这个问题是存在的，我也测试了，在固定表头的情况下，移动端滑动是会速度明显不一致，用的是官网的例子，是百分百出现的情况，我自己写了动态计算的，看什么时候有空整合下。

**Comment by muxw** [comment]
> 这个问题是存在的，我也测试了，在固定表头的情况下，移动端滑动是会速度明显不一致，用的是官网的例子，是百分百出现的情况，我自己写了动态计算的，看什么时候有空整合下。

我也遇到了移动端速度不一致的问题，可以具体说一下是怎么修改的么？
