### ISSUE TITLE
ERROR in ./~/.1.3.0@vue-easytable/libs/v-table/src/table.vue

### ISSUE THREAD

**Issue by ww18** [huangshuwei/vue-easytable#14]
ERROR in ./~/.1.3.0@vue-easytable/libs/v-table/src/table.vue
Module parse failed: /Users/oak-016/localgit/beidou/frontv2/node_modules/.1.3.0@vue-easytable/libs/v-table/src/table.vue Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <template>
|     <div class="v-table-views v-table-class" :style="{'width': internalWidth+'px'; 'height': getTableHeight+'px'}">

在table.vue， page.vue，select.vue中都有这个错误。
webpack打包的时候报的错

**Comment by huangshuwei** [comment]
感谢反馈，下午我看下

**Comment by huangshuwei** [comment]
首先保证是通过npm 安装。

从这个错误提示，应该是没有识别 .vue 文件的loader，你其他的vue文件可以正常编译吗？
> You may need an appropriate loader to handle this file type.

**Comment by huangshuwei** [comment]
我自安装了下，可以正常编译。应该是缺少 `vue-loader`。

如果你是使用的 webpack,配置信息可以参考vue-easytable中webpack 配置文件：
https://github.com/huangshuwei/vue-easytable/blob/master/webpack.config.js

**Comment by huangshuwei** [comment]
问题解决了没，先关了，有问题再反馈
