### ISSUE TITLE
vue-easyTable 表格，能否实现动态更新表格，根据后台获取的数据不同，保留原先的表格，将第二份数据中不同的数据插入到指定位置

### ISSUE THREAD

**Issue by dawayway** [huangshuwei/vue-easytable#149]
vue-easyTable 表格，能否实现动态更新表格，根据后台获取的数据不同，保留原先的表格，将第二份数据和第一份数据作比较，将不同的数据插入到指定位置或者表格后面

**Comment by huangshuwei** [comment]
如果要更新表格的数据，需要从后台获取然后给`table-data`重新赋值即可。
如果需要把差异的数据插入到指定的位置需要重新构造`table-data`数据，并重新给`table-data`赋值。
