### ISSUE TITLE
能否点击新增按钮会自动出现一个空白行以支持新增呢

### ISSUE THREAD

**Issue by Luke-Wang** [huangshuwei/vue-easytable#150]
能否点击新增按钮会自动出现一个空白行以支持新增呢。
示例，
![snipaste_2018-04-12_15-49-32](https://user-images.githubusercontent.com/20654507/38663301-0bd3ee50-3e69-11e8-97db-62d6aac83048.png)

**Comment by ly525** [comment]
这个可以，可以直接向 tableData 中新增一行即可。
