### ISSUE TITLE
requirejs下怎么使用

### ISSUE THREAD

**Issue by shiqinghe** [huangshuwei/vue-easytable#153]
requirejs下用示例代码会有以下报错：
vue.js:597 [Vue warn]: Unknown custom element: <v-table> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)

该怎么用呢

**Comment by imgwho** [comment]
请问解决了吗 @shiqinghe

**Comment by ly525** [comment]
没有提供可复现的例子，已经关闭
