### ISSUE TITLE
How can I put a dropdown menu in a cell in each line?

### ISSUE THREAD

**Issue by luisdesouza** [huangshuwei/vue-easytable#158]

**Comment by luisdesouza** [comment]
[http://i68.tinypic.com/2ur2quo.png](url)

**Comment by luisdesouza** [comment]
[https://imgur.com/a/NBnKP4w](url)

**Comment by ly525** [comment]
Ok, I got it. You can set `componentName` for column to use a component that with a dropdown.
See the [docs](http://doc.huangsw.com/vue-easytable/app.html#/table/customColumns)
