### ISSUE TITLE
支持动态合并单元格吗？

### ISSUE THREAD

**Issue by Jsonlih** [huangshuwei/vue-easytable#166]
新增一行数据的时候动态合并

**Comment by ly525** [comment]
麻烦提供能够复现的例子，比如 codepen 或者 jsfiddle。
Please provide a reproduction link, like codepen or jsfiddle

**Comment by ly525** [comment]
没有提供可复现的例子，已经关闭。
如果有问题，可以在该 issue 下继续讨论，我们会及时跟进
