### ISSUE TITLE
表格显示有问题

### ISSUE THREAD

**Issue by daminga** [huangshuwei/vue-easytable#167]
表格里面，比如点击表头，进入另一个表格界面，在另一个表格界面使用router返回的时候，表格显示有问题。表格的高度会变小，下面空出一片空白。

**Comment by daminga** [comment]
问一下，这个跟vux有冲突吗？vux的组件返回就那样了！vux xheader 返回

**Comment by daminga** [comment]
查找到原因了，已解决！

**Comment by daminga** [comment]
新问题：如果不选择自适应的话，表格就不能上下滑动了

**Comment by daminga** [comment]
尽量使用：height   自带的属性！ class  style里面的不管用

**Comment by daminga** [comment]
已经解决完了！

**Comment by ly525** [comment]
没有提供可复现的例子，已经关闭。
如果有问题，可以在该 issue 下继续讨论，我们会及时跟进
