### ISSUE TITLE
动态修改表格的数据时，表格会重绘，导致纵向自适应失效，怎么解决

### ISSUE THREAD

**Issue by NinjaJin** [huangshuwei/vue-easytable#168]
修改表格的data，v-table-views会刷新一下导致height样式改变，纵向自适应失效

**Comment by ly525** [comment]
麻烦提供能够复现的例子，比如 codepen 或者 jsfiddle。
Please provide a reproduction link, like codepen or jsfiddle

**Comment by ly525** [comment]
升级到最新版本试一下呢
