### ISSUE TITLE
IE浏览器部分表格不能正常显示

### ISSUE THREAD

**Issue by LunchFood** [huangshuwei/vue-easytable#17]
vue-easytable官网就能看到具体的表格

**Comment by huangshuwei** [comment]
恩恩，看到了，感谢反馈

**Comment by LunchFood** [comment]
今天做项目测试兼容性，结果IE打开就很尴尬，希望尽快修复，毕竟还是很好用的

**Comment by huangshuwei** [comment]
赞赞赞，我还以为没人用呢，尽快修复

**Comment by huangshuwei** [comment]
不过由于用的是vue, IE兼容性只能支持IE8以上

**Comment by LunchFood** [comment]
嗯，我们也只做到兼容IE8+

**Comment by huangshuwei** [comment]
ok,没问题

**Comment by LunchFood** [comment]
赞赞赞

**Comment by LunchFood** [comment]
我觉得 合并列不怎么好用，而且官网的实例也没有给tableData，这就让我们这些小白很茫然，不知道数据格式是怎么样的

**Comment by huangshuwei** [comment]
现在官网更新了，你再看下，可以直接在实例中看到`tableData`数据了

**Comment by LunchFood** [comment]
![qq 20171016153558](https://user-images.githubusercontent.com/22734894/31600105-c486ae1a-b287-11e7-9e8c-0e4292224425.png)
列合并我希望能够简单点

**Comment by huangshuwei** [comment]
> 我觉得 合并列不怎么好用...

合并列功能指的是这个吗
http://doc.huangsw.com/vue-easytable/app.html#/table?anchor=table-cell-merge

我觉得用起来还好吧，你就当做是html表格，找到要合并的列。需要列合并就赋值 `colspan`,需要 行合并 就 赋值`roswpan`

**Comment by huangshuwei** [comment]
>列合并我希望能够简单点

表头合并有点繁琐，不过目前没有太好的方法。等功能比较完善了再优化

**Comment by LunchFood** [comment]
大佬，这个判断合并列的方法，像我图片这种数据，大数据就会出现很多遍，然后选择第一个大数据进行合并

**Comment by huangshuwei** [comment]
> 大佬，这个判断合并列的方法，像我图片这种数据，大数据就会出现很多遍，然后选择第一个大数据进行合并

能否详细点，没太懂

**Comment by LunchFood** [comment]
![qq 20171016153558](https://user-images.githubusercontent.com/22734894/31600488-43f0126c-b289-11e7-8250-0e06e2699f16.png)
比如我这种的，tableData格式的话就不好写了

**Comment by huangshuwei** [comment]
你这张图表头和下面的列都没有对齐，可能只是原型图的问题。
如果要实现你上面这张图的效果，的确要写不少代码，不过即使你用html写一个table ,通过rowspan 和 cowspan 设置也是非常繁琐的。

**Comment by LunchFood** [comment]
嗯，我目前就是在解决上下宽度不对齐的问题，rowspan和cowspan确实繁琐，而且数据格式也不好定

**Comment by LunchFood** [comment]
大佬，给个微信，我们微信上面说吧，或者QQ

**Comment by huangshuwei** [comment]
微信和qq都不太方便啊，公司电脑不给安装，用手机码字能累死。还是这上面方便点，请谅解☺️

**Comment by LunchFood** [comment]
好的，还是希望大佬能够满足一下我这个需求，在网上找了许多，最后是通过element的Issues里面找到您的

**Comment by huangshuwei** [comment]
恩，现在是要解决浏览器兼容的问题，最近的几个版本我都是用chrome测试的，忽略了IE。我尽快修复。
关于如何优化使用合并列的问题，等有时间了我好好想想

**Comment by LunchFood** [comment]
好的

**Comment by huangshuwei** [comment]
已修复。
[已发布](https://github.com/huangshuwei/vue-easytable/releases/tag/1.3.4)，安装最新即可

**Comment by LunchFood** [comment]
好的，谢谢大佬
