### ISSUE TITLE
有做一个 mpvue 兼容的一个支持计划吗

### ISSUE THREAD

**Issue by fbigun** [huangshuwei/vue-easytable#173]
有做一个 mpvue 兼容的一个支持计划吗？

看到这个项目，最近又在 mpvue 做小程序，所以问问有没有这个支持。

**Comment by ly525** [comment]
不好意思，因为现在没有涉及小程序开发，暂时没有开发计划
我把放到计划内，在近期会了解下，看看 mpvue 和 easy-table 是否可以做兼容计划的可能性

也欢迎你提 pr
