### ISSUE TITLE
微信公众号中不能显示页码选择

### ISSUE THREAD

**Issue by sunriseyuen** [huangshuwei/vue-easytable#174]
微信公众号中不能显示页码选择

**Comment by ly525** [comment]
欢迎反馈😄
麻烦提供能够复现的例子，比如 codepen 或者 jsfiddle，让我们能够复现你的问题。
Please provide a reproduction link, like codepen or jsfiddle

**Comment by ly525** [comment]
没有提供可复现的例子，已经关闭。
如果有问题，可以在该 issue 下继续讨论，我们会及时跟进
