### ISSUE TITLE
渲染数据时按指定字段筛选。

### ISSUE THREAD

**Issue by yichangle** [huangshuwei/vue-easytable#18]
定义一个method，渲染表格数据的时候可以自动调用，从而依据返回结果控制该行是否显示。进一步可以通过该method加工数据，表格依据加工后的数据

**Comment by yichangle** [comment]
表格依据加工后的数据渲染。考虑效率，估计先在后台处理好数据，再开始渲染DOM可能会好些。

**Comment by huangshuwei** [comment]
就是添加过滤条件对吧。

**Comment by huangshuwei** [comment]
感谢提供宝贵的意见，准备抽出几天时间完善下，更新速度有点慢了。请谅解

**Comment by huangshuwei** [comment]
已实现，已发布
https://github.com/huangshuwei/vue-easytable/releases/tag/1.7.0
