### ISSUE TITLE
条件筛选的下拉怎么动态更改？

### ISSUE THREAD

**Issue by wlx10011101** [huangshuwei/vue-easytable#180]
我这边使用v-table的条件筛选功能，我的理解是，每次只要更新了tableData和columns这两个字段里面的数据，页面上的内容也会动态更新，但是实际的情况是，只有tableData的更改会生效，而即使columns的filters字段数据更新了，页面上也不会跟着动态更改？请问有啥办法可以解决，还是我这边使用上有问题？

**Comment by ly525** [comment]
你好，欢迎反馈。
麻烦提供能够复现的例子，比如 codepen 或者 jsfiddle，让我们能够复现你的问题。
Please provide a reproduction link, like codepen or jsfiddle

**Comment by wlx10011101** [comment]
vue代码文件如下，后缀改成vue就可以直接使用。
[TableWithSplit.txt](https://github.com/huangshuwei/vue-easytable/files/2036077/TableWithSplit.txt)

**Comment by ly525** [comment]
@wlx10011101 文件无法下载，此外我们不接受这种方式。请参照 Issue 规范

**Comment by ly525** [comment]
没有提供可复现的例子，已经关闭。
如果有问题，可以在该 issue 下继续讨论，我们会及时跟进
