### ISSUE TITLE
请问一下如何实现动态显示表头数据？

### ISSUE THREAD

**Issue by hownet** [huangshuwei/vue-easytable#181]
columns: [
                    {field: 'name', title:'姓名', width: 100, titleAlign: 'center',columnAlign:'center'},
                    {field: 'tel', title: '手机号码', width: 260, titleAlign: 'center',columnAlign:'center'},
                    {field: 'hobby', title: '爱好', width: 330, titleAlign: 'center',columnAlign:'center'},
                    {field: 'address', title: '地址', titleAlign: 'center',columnAlign:'left'}
                ]

这里面的数据我是根据上一个表格操作来动态加载的，现在调试返回的格式跟这一样，但就是不显示出来。刚转前端来学VUE，麻烦指点一下，谢谢。

**Comment by shenahobo** [comment]
你点击之后,加载数据,然后在赋值给 columns 就可以了, 如果你在同一个页面的话你就不能返回上一个表格了.

**Comment by ly525** [comment]
没有提供可复现的例子，已经关闭。
如果有问题，可以在该 issue 下继续讨论，我们会及时跟进

**Comment by ly525** [comment]
@shenahobo 非常感谢，很棒的回答
