### ISSUE TITLE
隐藏表头或者表中间插入一行总结

### ISSUE THREAD

**Issue by Apple-Flavor** [huangshuwei/vue-easytable#192]
我建了两个表，用的同样的表头，为了看起来像一张表，需要隐藏后面表的表头。怎么做？或者有别的办法实现:在表的任意位置插入一行总结而不是footer。

**Comment by ly525** [comment]
欢迎反馈
麻烦提供能够复现的例子，比如 codepen 或者 jsfiddle，让我们能够复现你的问题。
Please provide a reproduction link, like codepen or jsfiddle

请参照 [Issue 规范](https://github.com/huangshuwei/vue-easytable/wiki/Issue-%E8%A7%84%E8%8C%83)
