### ISSUE TITLE
可以按照第几行第几列的形式合并吗？现在似乎是按照相邻的行数合并的 有些相邻的行数并不想合并

### ISSUE THREAD

**Issue by aimchina** [huangshuwei/vue-easytable#194]
可以按照第几行第几列的形式合并吗？现在似乎是按照相邻的行数合并的 有些相邻的行数并不想合并

**Comment by aimchina** [comment]
![647ef0803f358501d45ae8f106eff351](https://user-images.githubusercontent.com/11752702/41575410-d6d6c386-73b4-11e8-8b96-b233dce729d6.jpg)

请看截图，只想合并A和A所在行的两个e，而不是把B或者C所在行的E也给合并了

**Comment by aimchina** [comment]
A  E
A  E
B  E
C  E
就是B和C的E不合并。不知道我表达清楚没有

**Comment by ly525** [comment]
可以在cell-merge中自定义实现
