### ISSUE TITLE
有个bug似乎，图片不显示，在开启横向自适应的情况下。

### ISSUE THREAD

**Issue by aimchina** [huangshuwei/vue-easytable#196]
用自定义列写了一个显示图片的列，根据接口传递过来的图片地址。但是开启横向自适应的情况下，图片不显示了。 不开启的情况下，图片能正常显示。这是为什么啊？

**Comment by aimchina** [comment]
组件名叫  table-img

**Comment by aimchina** [comment]
没有人遇到这个问题？

**Comment by ly525** [comment]
欢迎反馈
麻烦提供能够复现的例子，比如 codepen 或者 jsfiddle，让我们能够复现你的问题。
Please provide a reproduction link, like codepen or jsfiddle

请参照 [Issue 规范](https://github.com/huangshuwei/vue-easytable/wiki/Issue-%E8%A7%84%E8%8C%83)

**Comment by ly525** [comment]
没有提供可复现的例子，已经关闭。 如果有问题，可以在该 issue 下继续讨论，我们会及时跟进
