### ISSUE TITLE
多选存在的意义

### ISSUE THREAD

**Issue by luneice** [huangshuwei/vue-easytable#197]
多选删除该怎么实现？虽然选择时会有回调，自定义的方法如何获取选中的项？

**Comment by ly525** [comment]
请仔细阅读官方文档：[多选](http://doc.huangsw.com/vue-easytable/app.html#/table/selection)
更多请查看 Vue.js 官方文档中关于数组操作的章节

**Comment by luneice** [comment]
多选中事件触发才会回调，如果要实现多选删除的话，怎么拿到选中的索引呢？我只能开辟额外的数据，在多选事件触发时通过回调函数去保存，不知道有没有更好的方式实现？

**Comment by ly525** [comment]
没有提供可复现的例子，已经关闭。 如果有问题，可以在该 issue 下继续讨论，我们会及时跟进
