### ISSUE TITLE
自定义列自定义的组件不能加载

### ISSUE THREAD

**Issue by wing-king** [huangshuwei/vue-easytable#198]
自定义列自定义的组件不能加载

**Comment by wing-king** [comment]
Unknown custom element: <linkto> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by ly525** [comment]
欢迎反馈
麻烦提供能够复现的例子，比如 codepen 或者 jsfiddle，让我们能够复现你的问题。
Please provide a reproduction link, like codepen or jsfiddle

请参照 [Issue 规范](https://github.com/huangshuwei/vue-easytable/wiki/Issue-%E8%A7%84%E8%8C%83)

**Comment by ly525** [comment]
没有提供可复现的例子，已经关闭。 如果有问题，可以在该 issue 下继续讨论，我们会及时跟进
