### ISSUE TITLE
（补充问题）是否支持单选？

### ISSUE THREAD

**Issue by zlmai** [huangshuwei/vue-easytable#199]
是否有单选模式？
补充：表格有没有和多选功能（http://doc.huangsw.com/vue-easytable/app.html#/table/selection）对应的单选功能？就是不能批量全选，只能选择一条记录，比如，如果A已选，那么再选B时，A就会取消选中

**Comment by zlmai** [comment]
补充：表格有没有和多选功能（http://doc.huangsw.com/vue-easytable/app.html#/table/selection）对应的单选功能？就是不能批量全选，只能选择一条记录，比如，如果A已选，那么再选B时，A就会取消选中

**Comment by ly525** [comment]
请详细描述你的使用场景，或者你看到过的例子、草图

**Comment by ly525** [comment]
请仔细描述你的使用场景，或者你看到的实例、草图等

**Comment by ly525** [comment]
没有提供可复现的例子，已经关闭。 如果有问题，可以在该 issue 下继续讨论，我们会及时跟进
