### ISSUE TITLE
表格编辑

### ISSUE THREAD

**Issue by otaku1951** [huangshuwei/vue-easytable#2]
哥们，把单元格或行编辑的也给做了呗。

**Comment by huangshuwei** [comment]
好的，空了我把这个功能加上，好了通知你。

目前想法是：
在单元格内允许编辑，编辑结束后会触发回调函数

**Comment by otaku1951** [comment]
我是觉得把单元格的contenteditable这个属性打开应该就可以了，只是这个得在组件的option做个能配置的哈，毕竟不是所有人都想表格可编辑

**Comment by huangshuwei** [comment]
是的，这个会做一个配置开关，不过编辑完需要触发回调（客户端数据持久化或其他操作）

**Comment by otaku1951** [comment]
对对，回调可以有，多谢大神哈。

**Comment by huangshuwei** [comment]
😊

**Comment by huangshuwei** [comment]
@otaku1951 
编辑功能已经加上了，下载最新就可以使用了。效果如下：
http://doc.huangsw.com/vue-easytable/app.html#/table?anchor=table-cell-edit

**Comment by otaku1951** [comment]
收到，收到，多谢了😊
