### ISSUE TITLE
使用Vue.component('table-operation',{报错

### ISSUE THREAD

**Issue by ruanzy** [huangshuwei/vue-easytable#203]
webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:588 [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

**Comment by ruanzy** [comment]
好像是模板无法compile  要用render 函数

**Comment by ly525** [comment]
你在使用 vue-cli  初始化项目的时候，需要安装完整版的 vue.js， 不要安装 runtime-only， 这个没有解析模板的 compile 部分

**Comment by tolerious** [comment]
@ruanzy  在vue.config.js文件中如下配置即可。

```
module.exports = {
    configureWebpack: {
        resolve: {
            alias:{
                'vue$':'vue/dist/vue.esm.js'
            }
        }
    }
}
```
