### ISSUE TITLE
表格设置可编辑，然后填入数据后表格不显示数据。

### ISSUE THREAD

**Issue by zhangshichuan** [huangshuwei/vue-easytable#204]
1. 回调函数是正常调用的。 并且newValue能拿到。
2. this.tableData[rowIndex][field] 也能正常被赋值
3. 然后我继续给其他单元格填值，填了后有些时候就会自动把之前填了值但是不显示值的单元格的值给正常显示出来。

**Comment by zhangshichuan** [comment]
![1](https://user-images.githubusercontent.com/8280832/42760824-3a0cac56-893e-11e8-8581-8491afb4f13b.png)

**Comment by zhangshichuan** [comment]
如上： 生日和性别我已经填写了。回调函数和赋值都是正常的。

**Comment by zhangshichuan** [comment]
![3](https://user-images.githubusercontent.com/8280832/42761208-6f054412-893f-11e8-8e5d-0ce8cd61d3e2.png)

**Comment by zhangshichuan** [comment]
这是大致结构，我项目中使用的表格不止这一列，问题都是出现在生日和性别这两个字段上。欲哭无泪啊。不知道怎么回事。

**Comment by zhangshichuan** [comment]
因为值都是能正常修改并且也能更新到表格，但就是不显示。然后填写其他单元格后，就能正常显示出来了。

**Comment by ly525** [comment]
欢迎反馈
麻烦提供能够复现的例子，比如 codepen 或者 jsfiddle，让我们能够复现你的问题。
Please provide a reproduction link, like codepen or jsfiddle

请参照 [Issue 规范](https://github.com/huangshuwei/vue-easytable/wiki/Issue-%E8%A7%84%E8%8C%83)

**Comment by zhangshichuan** [comment]
问题已解决！ 因为生日和性别这2个对象的属性我没有声明，也没有给初始值。然后我编辑这2项单元格的时候，通过回调函数动态的扩充了我原来声明的对象属性。 所以就不能即使刷新出来。后来我在声明的时候就把这2个属性补充上，并设置初始值，就解决这个问题了。
