### ISSUE TITLE
有没有全局的配置表格行高及表格中字体和字号功能？

### ISSUE THREAD

**Issue by yichangle** [huangshuwei/vue-easytable#21]
如标题。

**Comment by huangshuwei** [comment]
设置表头行高以及表格体行高通过 [api 文档](http://doc.huangsw.com/vue-easytable/app.html#/table?anchor=table-api)设置，分别对应 `title-row-height` 和 `row-height`

字体和字号，默认依赖于外部的字体和字号。当然也对外开放了class 去控制，这个样式放到项目的样式表里即可（下次文档升级我加下说明）：
```
.v-table-class{
      /* 设置表格的字号和字体*/
}
```

**Comment by huangshuwei** [comment]
如果要全局的设置表头行高和表格体行高，建议通过vuex 设置，如 ：
```
rootState:{
   titleRowHeight:30,
   rowHeight:30
}
```

然后每个使用table的地方直接用就vuex中定义的常量就好了

**Comment by huangshuwei** [comment]
文档已更新，包含详细说明：
http://doc.huangsw.com/vue-easytable/app.html#/start

**Comment by yichangle** [comment]
谢谢！太棒啦。
