### ISSUE TITLE
作为一个后端程序员表示不知道怎么使用

### ISSUE THREAD

**Issue by zhuSilence** [huangshuwei/vue-easytable#22]
watch这个组件好久了，最近有新需求刚好能使用一下，但是不是一个专业的前端，不能熟练的使用，不知道是否能提供类似一个JS插件的方式直接引用呢？谢谢。

**Comment by huangshuwei** [comment]
目前还不支持通过链接引入组件，等我做好了给你提供一个

**Comment by zhuSilence** [comment]
好的，谢谢啦。

**Comment by 873991530** [comment]
期待，快些出来啊

**Comment by huangshuwei** [comment]
@zhuSilence @873991530 
已经实现并发布了，久等了。
具体使用方式参考文档：
http://doc.huangsw.com/vue-easytable/app.html#/install

**Comment by zhuSilence** [comment]
@huangshuwei  好的，辛苦博主。马上试用起来。

**Comment by huangshuwei** [comment]
好的，有问题反馈

**Comment by zhuSilence** [comment]
@huangshuwei  博主有对"data-list"这个id做什么操作吗？
![image](https://user-images.githubusercontent.com/8224393/32216947-78eda580-bdf4-11e7-8fa1-9f23673ca851.png)
发现如果使用这个id作为元素id，就会出现表格错位
![image](https://user-images.githubusercontent.com/8224393/32216994-94dd2e78-bdf4-11e7-8b00-e344d9b75729.png)

**Comment by huangshuwei** [comment]
@zhuSilence 
你把完整的实例贴出来，我看下，应该和id没关系，组件里没有对`data-list`做设置

**Comment by zhuSilence** [comment]
@huangshuwei 就用的是你页面上贴的代码，只是把id换掉了
![image](https://user-images.githubusercontent.com/8224393/32217738-efd8f63e-bdf6-11e7-8066-4b7d0265c406.png)

**Comment by zhuSilence** [comment]
@huangshuwei 如果说把"data-list"里面的‘-’去掉，就可以

**Comment by huangshuwei** [comment]
我刚才把容器的id改成了`data-list`没有问题。你全局搜下，看下是不是有样式作用到了 `data-list`上面。

**Comment by zhuSilence** [comment]
ok，那应该就是这个问题了。谢谢，很好用

**Comment by huangshuwei** [comment]
感谢支持😂
