### ISSUE TITLE
自定义组件不支持import吗？

### ISSUE THREAD

**Issue by CrytisMT** [huangshuwei/vue-easytable#220]
列的自定义组件import之后，一直报错提示未注册组件，但其实已经注册了，而且模板里手动使用自定义组件也是可以的，是不是不支持import的组件？

**Comment by ly525** [comment]
自定义组件目前需要写成全局注册，也就是通过 vue.component来注册

**Comment by comeOutBing** [comment]
有什么方式可以 不用注册全局组件吗，因为这样会感觉 全局组件会很多，
