### ISSUE TITLE
添加列后表格变空白

### ISSUE THREAD

**Issue by CrytisMT** [huangshuwei/vue-easytable#221]
```
<VTable :columns="columns" :table-data="tableData" style="width:100%" is-horizontal-resize
		        :cell-edit-done="cellEditDone" @on-custom-comp="rowAction" columns-width-drag>

</VTable>
```
手动用  this.columns.splice添加一个column后，table会变成空白的。。。。
打开一下控制台又能显示了

**Comment by ly525** [comment]
@CrytisMT 请升级到 v.1.7.2 试试，已经修正
https://github.com/huangshuwei/vue-easytable/blob/9967066cb9fa30808c11c8f4b41f2c963eab09cb/packages/v-table/src/table.vue#L896-L901
