### ISSUE TITLE
数据添加后出现空白

### ISSUE THREAD

**Issue by jarryyou** [huangshuwei/vue-easytable#241]
按文档中设置好数据，有时会出现空白。查看元素发现数据已经渲染，当浏览器窗口大小出现变化时，表格结构便会展示出来，或者当打开控制台，拖动控制台高度的时候，表格结构也会展示出来。浏览器窗口不变，任何操作都不能使表格结构展现。

**Comment by ly525** [comment]
请更新到1.7.2版本再试试，如果有问题，可以重新打开这个issue
