### ISSUE TITLE
按照教程添加数据后，表头不显示

### ISSUE THREAD

**Issue by weidesh** [huangshuwei/vue-easytable#246]
![vue-easytable](https://user-images.githubusercontent.com/8555253/47143438-b5950f00-d2f7-11e8-851c-7ca4656ff262.png)
` <h1>各腔温度随转角变化曲线</h1>`
` <hr />`
`      <v-table`
`              class="table-main"`
 `             is-horizontal-resize`
 `             :vertical-resize-offset='40'`
`              :height='378'`
 `             style="width:100%"`
 `             :row-height="38"`
`              :columns="columns"`
 `             :table-data="tempData"`
`              row-hover-color="#eee"`
`              row-click-color="#edf7ff"`
 `     >`
`      </v-table>`
columns从本地js文件中import

**Comment by ly525** [comment]
请提供可以复现的事例！另外请排版代码

**Comment by ly525** [comment]
closed because we could not reproduce
