### ISSUE TITLE
如何让一列中某些单元格可编辑某些不编辑?

### ISSUE THREAD

**Issue by peak-gf** [huangshuwei/vue-easytable#248]
大神，我在使用你的表格时，在某一列开启编辑，在某些单元格自定义组件，但是开启编辑模式，这个单元格就无法正常显示自定义组件，一直没法解决，求帮助。
如何在一列中某些单元格可编辑，某些不可编辑?

**Comment by ly525** [comment]
这个可以通过自定义组件来实现，可以根据 rowdata，column name和 rowindex 结合自己的业务逻辑进行判断

**Comment by ly525** [comment]
比如不可编辑就返回一个正常的div，可以编辑就返回一个editable的div即可
