### ISSUE TITLE
引入css不生效

### ISSUE THREAD

**Issue by rickywu** [huangshuwei/vue-easytable#249]
import 'vue-easytable/libs/themes-base/index.css';

图标显示成这样
![image](https://user-images.githubusercontent.com/442398/47891930-3cb5bb80-de90-11e8-96dd-55cd4015029c.png)

在Windows上也有相同问题，但莫名其妙又消失了，Linux始终无法正常显示

**Comment by ly525** [comment]
应该是网络问题，字体资源加载失败导致的
