### ISSUE TITLE
表格数据刷新的问题

### ISSUE THREAD

**Issue by onlyLiuMing** [huangshuwei/vue-easytable#252]
感谢您的工具，非常好用！在使用中出现了个数据刷新的问题：
    当表格数据中同时存在 _checked,_disabled时（部分数据_checked=true;部分_disabled=true），多数情况_checked不会被显示，当我不使用disable属性时checked属性会正常显示

**Comment by ly525** [comment]
欢迎反馈
麻烦提供能够复现的例子，比如 codepen 或者 jsfiddle，让我们能够复现你的问题。
Please provide a reproduction link, like codepen or jsfiddle

请参照 [Issue 规范](https://github.com/huangshuwei/vue-easytable/wiki/Issue-%E8%A7%84%E8%8C%83)

**Comment by ly525** [comment]
closed because we couldn't reproduce it
