### ISSUE TITLE
如何向自定义列的组件传参，现在只能传固定参数

### ISSUE THREAD

**Issue by 693263410** [huangshuwei/vue-easytable#255]
如题

**Comment by 693263410** [comment]
http://doc.huangsw.com/vue-easytable/app.html#/table/customColumns

**Comment by ly525** [comment]
可以描述一些具体场景，以便衡量需求

**Comment by zhouxianjun** [comment]
可以使用h 编译匿名组件吗

**Comment by ly525** [comment]
@zhouxianjun  请具体描述你的问题

**Comment by zhouxianjun** [comment]
类似这种：
![image](https://user-images.githubusercontent.com/5254523/52999895-f47fd080-3461-11e9-88b8-1abc7244d4a9.png)
https://segmentfault.com/l/1500000008892728

**Comment by ly525** [comment]
@zhouxianjun 可以考虑支持，不过现在还没有。其实自定义组建和通过 createElement 也就是你说的h 本质上是一回事了
