### ISSUE TITLE
主从表

### ISSUE THREAD

**Issue by xunqi** [huangshuwei/vue-easytable#256]
该插件能实现主从表表吗，有例子吗？谢谢

**Comment by ly525** [comment]
> 该插件能实现主从表表吗，有例子吗？谢谢

你说的主从表是指？请给出事例或者详细说明

**Comment by ly525** [comment]
欢迎反馈
麻烦提供能够复现的例子，比如 codepen 或者 jsfiddle，让我们能够复现你的问题。
Please provide a reproduction link, like codepen or jsfiddle

请参照 [Issue 规范](https://github.com/huangshuwei/vue-easytable/wiki/Issue-%E8%A7%84%E8%8C%83)
