### ISSUE TITLE
包依赖问题

### ISSUE THREAD

**Issue by lijianfeigeek** [huangshuwei/vue-easytable#257]
为什么 vue-easytable 安装在 devDependencies  下 ，dependencies 发布包也能用？

**Comment by lijianfeigeek** [comment]
为什么 vue-easytable 安装在 dependencies  不能使用呢？

**Comment by ly525** [comment]
欢迎反馈
麻烦提供能够复现的例子，比如 codepen 或者 jsfiddle，让我们能够复现你的问题。
Please provide a reproduction link, like codepen or jsfiddle

请参照 [Issue 规范](https://github.com/huangshuwei/vue-easytable/wiki/Issue-%E8%A7%84%E8%8C%83)
