### ISSUE TITLE
动态创建字段，整个表格会空白，求解决~

### ISSUE THREAD

**Issue by mexhfl** [huangshuwei/vue-easytable#261]
首先非常感谢作者为我们提供这么好用的插件！使用过程中遇到一些问题：动态添加表格字段，表格会变空白，触发窗口大小变化表格即恢复正常。我暂且通过手动调用组件tableResize()方法解决此问题，但是这并不是长久之计，还望作者帮我们解决下，期待版本更新，感谢

**Comment by ly525** [comment]
好的，是否可以提供复现demo，方便我们进行测试？

**Comment by ly525** [comment]
已经修复，请更新到 v1.7.2 及以上版本
