### ISSUE TITLE
vue-loader 依赖版本为 12.2.1 在 vue-cli 3.0 中报错

### ISSUE THREAD

**Issue by hcwhan** [huangshuwei/vue-easytable#266]
```
Module build failed (from ./node_modules/vue-loader/index.js):

TypeError: Cannot read property 'vue' of undefined
    at Object.module.exports (D:\XXXX\node_modules\vue-loader\lib\loader.js:52:48)
````

**Comment by ly525** [comment]
请提供可复现的 demo

**Comment by hcwhan** [comment]
在 最新的 vue-cli 3.5.1 中 新建一个空项目
在引入 vue-easytable 并使用后
yarn serve 运行报错 原因就是 vue-loader 版本 太老 与webpack 4 不兼容
demo:  https://github.com/hcwhan/table-empty-demo

**Comment by gokigoks** [comment]
Hello! also having this error.. Using webpack with Laravel-mix.

**Comment by xingzhichen** [comment]
解决没。

**Comment by hcwhan** [comment]
> 解决没。

手动安装 vue-loader  指定最新版本
`yarn add --dev vue-loader`

**Comment by gokigoks** [comment]
Yes. the current workaround is using yarn to install every package, or just  yarn to install vue-loader.
