### ISSUE TITLE
为什么不支持数据双向绑定

### ISSUE THREAD

**Issue by lomoye** [huangshuwei/vue-easytable#27]
有个需求就是某些列的值是根据其他值计算出来的，现在我改了数据，但是表格的显示不会自动刷新。我该如何解决？

**Comment by huangshuwei** [comment]
你用最新版本试试，最新版本`table-data` watch 方式改为了 deep watch。之前的确有这个问题。
有问题再反馈

**Comment by lomoye** [comment]
1.3.5是最新版么。我看了里面的table.vue组件里对table-data的watch方式没有改成deep watch哎。

**Comment by huangshuwei** [comment]
不好意思，刚才发布打包出现了点问题。
已发布：
https://github.com/huangshuwei/vue-easytable/releases/tag/1.3.6

**Comment by huangshuwei** [comment]
先关了，有问题再反馈
