### ISSUE TITLE
vue-easytable分页加载大量数据

### ISSUE THREAD

**Issue by dlsyaim** [huangshuwei/vue-easytable#270]
vue-easytable分页加载大量数据的时候。结合分页，每次前台只获取要显示的数据，大神能否给个JSON带多少条记录的JSON数据格式

**Comment by ly525** [comment]
请仔细描述你的问题，让开发者能理解你的意思

**Comment by dlsyaim** [comment]
vue-easytable分页加载后台大量数据的时候。不可能一次把所有数据都加载过来。我想前台传参数。比如加载50条。后台取50条数据的JSON返回给前台，和后台一共有多少条记录也返回，比如。类似这种数据格式
{"Count":"14","DataList":[{"VbtID":14,"EquipMentID":14,"VbtDay":200,"VbtMonth":6000,"VbtYear":60000,"AddTime":"2019-02-20 09：00：00"},{"VbtID":13,"EquipMentID":13,"VbtDay":200,"VbtMonth":6000,"VbtYear":60000,"AddTime":"2019-02-20 09：00：00"},{"VbtID":12,"EquipMentID":12,"VbtDay":200,"VbtMonth":6000,"VbtYear":60000,"AddTime":"2019-02-20 09：00：00"},{"VbtID":11,"EquipMentID":11,"VbtDay":200,"VbtMonth":6000,"VbtYear":60000,"AddTime":"2019-02-20 09：00：00"},{"VbtID":10,"EquipMentID":10,"VbtDay":200,"VbtMonth":6000,"VbtYear":60000,"AddTime":"2019-02-20 09：00：00"},{"VbtID":9,"EquipMentID":9,"VbtDay":200,"VbtMonth":6000,"VbtYear":60000,"AddTime":"2019-02-20 09：00：00"},{"VbtID":8,"EquipMentID":8,"VbtDay":200,"VbtMonth":6000,"VbtYear":60000,"AddTime":"2019-02-20 09：00：00"},{"VbtID":7,"EquipMentID":7,"VbtDay":200,"VbtMonth":6000,"VbtYear":60000,"AddTime":"2019-02-20 09：00：00"},{"VbtID":6,"EquipMentID":6,"VbtDay":200,"VbtMonth":6000,"VbtYear":60000,"AddTime":"2019-02-20 09：00：00"},{"VbtID":5,"EquipMentID":5,"VbtDay":200,"VbtMonth":6000,"VbtYear":60000,"AddTime":"2019-02-20 09：00：00"}]}
请教下大神。有没有类似的Demo

**Comment by ly525** [comment]
这个把前端分页的模式改成后端分页的模式就可以了，easytable 是支持的

**Comment by ly525** [comment]
具体可以看下文档里面的分页部分

**Comment by ly525** [comment]
有问题可以再提问，建议先看看搜一些资料先了解下怎么做。这个一般性的表格都是支持的

**Comment by dlsyaim** [comment]
大神，可以给一个完整的JSON数据格式吗。带总共多少条，当前页的JSOn。我这后台好模仿这给我拼接
