### ISSUE TITLE
在ie浏览器情况下不能使用自定义，

### ISSUE THREAD

**Issue by liugh001** [huangshuwei/vue-easytable#275]
在IE浏览器情况下不能使用自定义，

**Comment by ly525** [comment]
请提供可以复现的版本，已经 IE 的版本

**Comment by liugh001** [comment]
> 请提供可以复现的版本，以及IE的版本

vue.js版本是
/*!
 * Vue.js v2.5.20
 * (c) 2014-2018 Evan You
 * Released under the MIT License.
 */
ie浏览器是所以版本都有问题啊！！你自己随便写个简单的表格然后加个分页和自定义列就知道了
