### ISSUE TITLE
可否支持在组件外部修改 v-pagination 组件的属性呢？

### ISSUE THREAD

**Issue by rxliuli** [huangshuwei/vue-easytable#276]
## 场景

吾辈在使用 `v-pagination` 组件时，需要在选择一个分类的同时重置当前页数为 1，然而 `v-pagination` 组件并未进行变化。
所以吾辈在想，能否提供一种方式，让吾辈能够在组件外部修改 `<v-pagination` 的属性呢？

**Comment by ly525** [comment]
在 [分页组件-官方文档](http://doc.huangsw.com/vue-easytable/app.html#/pagination?anchor=page-api) 中，有 `pageIndex` 的API，你可以直接修改 pageIndex，这样就可以达到你想要的效果了

Demo： https://jsfiddle.net/18m2730d/
