### ISSUE TITLE
表格没有点击展开功能

### ISSUE THREAD

**Issue by leaper1** [huangshuwei/vue-easytable#28]
点击表格展开功能没有

**Comment by leaper1** [comment]
类似的饿了么前端UI里面的表格展开，然后点击按钮和展开内容是自定义

**Comment by huangshuwei** [comment]
好的，已经在开发了

**Comment by sunriseyuen** [comment]
http://blog.hypers.io/2017/09/03/rsuite-table/tree.png?_=7471652

展开是不是这个样子呢？
如果是这个样子就好了

**Comment by kevinding0218** [comment]
非常期待这个功能的开发！

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
