### ISSUE TITLE
我需要一个tfoot来显示一些汇总统计信息

### ISSUE THREAD

**Issue by jinfang134** [huangshuwei/vue-easytable#3]
如题，不过，如果在列属性里能加上自动求和的属性配置就最好了。

**Comment by huangshuwei** [comment]
可以，这个我要考虑下

**Comment by yichangle** [comment]
这功能如果能尽快实现就太棒了。

**Comment by huangshuwei** [comment]
各位久等了，footer 汇总功能已支持

实例：
http://localhost:63342/vue-easytable/dist/app.html?_ijt=ji129qv629k711n66iq6anenca#/table?anchor=table-footer-summary

发布更新：
https://github.com/huangshuwei/vue-easytable/releases/tag/1.4.0

**Comment by huangshuwei** [comment]
先关掉了，有问题再反馈

**Comment by zhuSilence** [comment]
你的这个实例地址是本地的，贴错了吧

**Comment by huangshuwei** [comment]
@zhuSilence 是的，昨天加班搞的，有点疲惫了，不好意思。已纠正。😂

**Comment by zhuSilence** [comment]
博主辛苦， 不过还是希望尽快能解决 #22 😂😂😂

**Comment by huangshuwei** [comment]
@zhuSilence 再不实现都不好意思回复你了😅
