### ISSUE TITLE
表格的标题和内容数据支持放在vuex中吗？

### ISSUE THREAD

**Issue by yichangle** [huangshuwei/vue-easytable#30]
我需要导入Excel，因此表格的结构不是固定的，想通过js-xlsx插件读取数据到vuex中，表格所在页面将tableData,columns,titleRows定义成计算字段，貌似表格不能更新，也可能是我不熟悉。

**Comment by huangshuwei** [comment]
可以的，你安装最新版再试下，最新版本watch方式改为了deep watch。
https://github.com/huangshuwei/vue-easytable/releases/tag/1.3.6

有问题再反馈

**Comment by yichangle** [comment]
更新版本果然可以😄。谢谢！

**Comment by yichangle** [comment]
表格内的子组件能通过事件方式向父组件通信吗？

**Comment by huangshuwei** [comment]
> 表格内的子组件能通过事件方式向父组件通信吗？

目前不可以，如果有复杂的数据交互，可以通过 vuex 去处理。
