### ISSUE TITLE
is there a english documentation?

### ISSUE THREAD

**Issue by LeFnord** [huangshuwei/vue-easytable#307]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能**
**Is your feature request related to a problem? Please describe.**

**描述下，你希望得到的什么解决方案 **
**Describe the solution you'd like**

**是否有不错的替代方案**
**Describe alternatives you've considered**

**附加信息**
**Additional context**

**Comment by wrdickson** [comment]
I've found that by going to http://doc.huangsw.com/vue-easytable/app.html#/intro using Chrome, and having Chrome translate to English, you can more or less figure out what's going on.  Good luck!

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
