### ISSUE TITLE
固定列设置

### ISSUE THREAD

**Issue by sunriseyuen** [huangshuwei/vue-easytable#31]
固定列 设置在  {field: 'name', width: 100, columnAlign: 'center', isFrozen: true}, 很不合理，
固定列只要设置一个数字就可以了，固定左边3列，设置为3.设置为字段的一个属性，又不能固定中间的列。

**Comment by huangshuwei** [comment]
像你说的这种方式，我实现起来其实更方便。
之所以现在是在需要固定的列设置`isFrozen`属性，因为有些场景下列信息是通过后端直接返回的，如果固定的列不是前几列，那么返回的数据结构也需要调整。
反之如果只通过`isFrozen`属性设置，列的顺序无需调整。

**Comment by sunriseyuen** [comment]
是的，只需要设定一个数字，会简化实现。假设固定的不是前几列，数据处理后后再传给vtable，而设置一个列数，还有一个好处，可以由客户端临时设定一个冻结列数，像现在调整大小的效果一样。

**Comment by huangshuwei** [comment]
是的，实现方式不同。
