### ISSUE TITLE
分页组件箭头那个小图标无法显示，index.css也引入了

### ISSUE THREAD

**Issue by chanyipiaomiao** [huangshuwei/vue-easytable#315]
使用方式是: CDN方式引入 index.css也是在本地服务器上
![image](https://user-images.githubusercontent.com/1332794/64525714-0b214280-d334-11e9-81c1-4c4fa948ae39.png)
如图所示

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
