### ISSUE TITLE
表体某个td内容过多，要求显示全部自动换号

### ISSUE THREAD

**Issue by FUHUALUN** [huangshuwei/vue-easytable#317]
默认样式是规定了列宽之后，内容超出列宽以...显示，需求是超出列宽之后的内容在当前td自动换行显示，哪个大神教教啊

**Comment by FUHUALUN** [comment]
再次研究发现，每个td里面还有一个div，去掉三行代码
white-space: nowrap;
word-wrap: normal;
overflow:hidden;
发现可以自动换行，但是内容换行之后跑到下面的td去了，每个td的高度应设置自适应填充，超出自动撑大，还在研究，若有相同问题的可参考

**Comment by annTTL** [comment]
只能自定义单元格组件来换行显示

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
