### ISSUE TITLE
列多的情况下，可以有水平滚动条吗？

### ISSUE THREAD

**Issue by huobaiyu** [huangshuwei/vue-easytable#321]
列多的情况下，每列都显示不全，能否固定每列的宽度加水平滚动条

**Comment by zhuanjiaozm** [comment]
@huobaiyu 请问下解决了吗？官方api中有滚动条出现（表格横向自适应 这部分），但是自己写的怎么都没有，不知道哪里出错了

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
