### ISSUE TITLE
项目依赖"vue-loader"该升级啦！

### ISSUE THREAD

**Issue by cxgreat2014** [huangshuwei/vue-easytable#323]
**Describe the bug 仔细描述这个 Bug **
简明扼要描述一下 这个 Bug
build报错：
build Cannot read property 'vue' of undefined

**To Reproduce 复现步骤**
最新版本vue创建项目之后安装本包，然后直接build报错

**Expected behavior 期待的行为**
 简明扼要描述下 你期待的正确结果是什么？
能正常build

# 解决方案：

https://segmentfault.com/q/1010000016192250

直接把 `vue-loader` 升级最新版就好

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
