### ISSUE TITLE
table不支持宽度自适应父元素么？

### ISSUE THREAD

**Issue by tolerious** [huangshuwei/vue-easytable#324]
必须要指定一个固定的宽度么？ width

```  
 <v-table
          :columns="columns"
          :table-data="tableData"
         is-horizontal-resize
         style="width:100%"
        ></v-table>
```

**Comment by tolerious** [comment]
![image](https://user-images.githubusercontent.com/2922120/68293635-543e0a80-00c9-11ea-923f-d89ecbbcf5c0.png)

**Comment by tolerious** [comment]
昨天的列显示不出来了。

**Comment by tolerious** [comment]
@huangshuwei @ly525

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
