### ISSUE TITLE
建议增加一项筛选功能!

### ISSUE THREAD

**Issue by Zzeo** [huangshuwei/vue-easytable#33]
表格中每一行数据有且仅有两种状态,(启用/禁用),在表头相应列能对数据进行筛选展示,如下图:
![image](https://user-images.githubusercontent.com/26971142/32204471-629fc30a-be24-11e7-97b8-77d4a5c7bbf6.png)

**Comment by huangshuwei** [comment]
和 #18 重复
尽快实现
