### ISSUE TITLE
Colspan and Rowspan alignment issue in vue easytable

### ISSUE THREAD

**Issue by ramanangru** [huangshuwei/vue-easytable#334]
Hi, 
   I am trying to use rowspan and colspan in the table header, but facing alignment issue. following is the code i used.

Vue Data:
`data() {
    return {
      emptyRows: [],
      footer: [],
      tableData: [
        {
          trackCode: '1203', progress: '25', rate: '20', hours: '35', amount: '750', actrate: '20', acthours: '35', actamount: '750', varrate: '20', varhours: '35', varamount: '750', billingCost: '3500'
        },
        {
          trackCode: '1204', progress: '30', rate: '20', hours: '35', amount: '750', actrate: '20', acthours: '35', actamount: '750', varrate: '20', varhours: '35', varamount: '750', billingCost: '3500'
        },
        {
          trackCode: '1205', progress: '25', rate: '20', hours: '35', amount: '750', actrate: '20', acthours: '35', actamount: '750', varrate: '20', varhours: '35', varamount: '750', billingCost: '3500'
        },
        {
          trackCode: '1206', progress: '30', rate: '20', hours: '35', amount: '750', actrate: '20', acthours: '35', actamount: '750', varrate: '20', varhours: '35', varamount: '750', billingCost: '3500'
        },
        {
          trackCode: '1207', progress: '25', rate: '20', hours: '35', amount: '750', actrate: '20', acthours: '35', actamount: '750', varrate: '20', varhours: '35', varamount: '750', billingCost: '3500'
        },
        {
          trackCode: '1208', progress: '30', rate: '20', hours: '35', amount: '750', actrate: '20', acthours: '35', actamount: '750', varrate: '20', varhours: '35', varamount: '750', billingCost: '3500'
        },
        {
          trackCode: '1209', progress: '25', rate: '20', hours: '35', amount: '750', actrate: '20', acthours: '35', actamount: '750', varrate: '20', varhours: '35', varamount: '750', billingCost: '3500'
        },
        {
          trackCode: '1210', progress: '30', rate: '20', hours: '35', amount: '750', actrate: '20', acthours: '35', actamount: '750', varrate: '20', varhours: '35', varamount: '750', billingCost: '3500'
        },
        {
          trackCode: '1211', progress: '25', rate: '20', hours: '35', amount: '750', actrate: '20', acthours: '35', actamount: '750', varrate: '20', varhours: '35', varamount: '750', billingCost: '3500'
        },
        {
          trackCode: '1212', progress: '30', rate: '20', hours: '35', amount: '750', actrate: '20', acthours: '35', actamount: '750', varrate: '20', varhours: '35', varamount: '750', billingCost: '3500'
        },
        {
          trackCode: '1213', progress: '25', rate: '20', hours: '35', amount: '750', actrate: '20', acthours: '35', actamount: '750', varrate: '20', varhours: '35', varamount: '750', billingCost: '3500'
        },
        {
          trackCode: '1214', progress: '30', rate: '20', hours: '35', amount: '750', actrate: '20', acthours: '35', actamount: '750', varrate: '20', varhours: '35', varamount: '750', billingCost: '3500'
        },
        {
          trackCode: '1215', progress: '25', rate: '20', hours: '35', amount: '750', actrate: '20', acthours: '35', actamount: '750', varrate: '20', varhours: '35', varamount: '750', billingCost: '3500'
        },
        {
          trackCode: '1216', progress: '30', rate: '20', hours: '35', amount: '750', actrate: '20', acthours: '35', actamount: '750', varrate: '20', varhours: '35', varamount: '750', billingCost: '3500'
        },
        {
          trackCode: '1217', progress: '25', rate: '20', hours: '35', amount: '750', actrate: '20', acthours: '35', actamount: '750', varrate: '20', varhours: '35', varamount: '750', billingCost: '3500'
        },
        {
          trackCode: '1218', progress: '30', rate: '20', hours: '35', amount: '750', actrate: '20', acthours: '35', actamount: '750', varrate: '20', varhours: '35', varamount: '750', billingCost: '3500'
        },
        {
          trackCode: '1219', progress: '25', rate: '20', hours: '35', amount: '750', actrate: '20', acthours: '35', actamount: '750', varrate: '20', varhours: '35', varamount: '750', billingCost: '3500'
        },
        {
          trackCode: '1220', progress: '30', rate: '20', hours: '35', amount: '750', actrate: '20', acthours: '35', actamount: '750', varrate: '20', varhours: '35', varamount: '750', billingCost: '3500'
        }
      ],
      columns: [
        {
          field: 'trackCode',
          width: 230,
          columnAlign: 'center',
          isResize: true
        },
        {
          field: 'progress',
          width: 100,
          columnAlign: 'center',
          isEdit: true,
          formatter(rowData, rowIndex, pagingIndex, field) {
            return `<span class='cell-edit-color'>${rowData[field]}</span>`;
          },
          isResize: true
        },
        { field: 'rate', width: 100, columnAlign: 'center' },
        { field: 'hours', width: 100, columnAlign: 'center' },
        { field: 'amount', width: 100, columnAlign: 'center' },
        { field: 'actrate', width: 100, columnAlign: 'center' },
        { field: 'acthours', width: 100, columnAlign: 'center' },
        { field: 'actamount', width: 100, columnAlign: 'center' },
        { field: 'varrate', width: 100, columnAlign: 'center' },
        { field: 'varhours', width: 100, columnAlign: 'center' },
        { field: 'varamount', width: 100, columnAlign: 'center' },
        {
          field: 'billingCost',
          width: 200,
          columnAlign: 'center'
        }
      ],
      titleRows: [
        [
          {
            fields: ['trackCode'], title: 'Tracking Code', titleAlign: 'center', rowspan: 2, colspan: 1
          },
          {
            fields: ['progress'], title: 'Progress (%)', titleAlign: 'center', rowspan: 2, colspan: 1
          },
          {
            fields: ['rate', 'hours', 'amount'], title: 'Estimate', titleAlign: 'center', colspan: 3, rowspan: 1
          },
          {
            fields: ['actrate', 'acthours', 'actamount'], title: 'Actual', titleAlign: 'center', colspan: 3, rowspan: 1
          },
          {
            fields: ['varrate', 'varhours', 'varamount'], title: 'Variance', titleAlign: 'center', colspan: 3, rowspan: 1
          },
          {
            fields: ['billingCost'], title: 'Billing Cost', titleAlign: 'center', rowspan: 2, colspan: 1
          }
        ],
        [{ fields: ['rate'], title: 'Rate', titleAlign: 'center' },
          { fields: ['hours'], title: 'Hours', titleAlign: 'center' },
          { fields: ['amount'], title: 'Amount ($)', titleAlign: 'center' },
          { fields: ['actrate'], title: 'Rate', titleAlign: 'center' },
          { fields: ['acthours'], title: 'Hours', titleAlign: 'center' },
          { fields: ['actamount'], title: 'Amount ($)', titleAlign: 'center' },
          { fields: ['varrate'], title: 'Rate', titleAlign: 'center' },
          { fields: ['varhours'], title: 'Hours', titleAlign: 'center' },
          { fields: ['varamount'], title: 'Amount ($)', titleAlign: 'center' }
        ]
      ]
    };
  }`

Template Code:
`<v-table
      v-if="tableData"
      style="width:100%"
      :height="300"
      :min-height="260"
      is-horizontal-resize
      :columns="columns"
      :table-data="tableData"
      :title-rows="titleRows"
      row-hover-color="#eee"
      row-click-color="#edf7ff"
      :cell-edit-done="cellEditDone"
      :footer-cell-class-name="setFooterCellClass"
      :footer="footer"
      :footer-row-height="40"
    ></v-table>`

Please find the attachment of the image file, how it looks in the UI
![Screenshot from 2020-06-15 11-05-48](https://user-images.githubusercontent.com/22755422/84659945-cc10c500-af35-11ea-89cb-f96a37cc7644.png)

**Comment by ramanangru** [comment]
Due to the alignment issue, the foorer is not visible. please check the header row

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
