### ISSUE TITLE
提一个npm包 package.json devDependencies 依赖bug

### ISSUE THREAD

**Issue by xiaogaofudao** [huangshuwei/vue-easytable#335]
npm 包文件已经被 webpack3 打包了，依赖项其实是不需要内容的。下载npm包发现 devDependencies 存在 webpack3 等其他无用的依赖。造成 npm i vue-easytable 后会下载 webpack 和项目的 webpack4 冲突。希望作者能在发布包的 package.json 去掉依赖项

**Comment by xiaogaofudao** [comment]
建议开发一个 package.json。打包发布单独一个。互不干扰

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
