### ISSUE TITLE
编辑cell 里支持 下拉框、时间控件操作吗？看文档没找到

### ISSUE THREAD

**Issue by spiritelf** [huangshuwei/vue-easytable#336]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能**
**Is your feature request related to a problem? Please describe.**

**描述下，你希望得到的什么解决方案 **
**Describe the solution you'd like**

**是否有不错的替代方案**
**Describe alternatives you've considered**

**附加信息**
**Additional context**

**Comment by huangshuwei** [comment]
不支持，编辑功能建议配合弹窗使用

**Comment by spiritelf** [comment]
那支持一些验证吗？

**Comment by huangshuwei** [comment]
Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
