### ISSUE TITLE
Title筛选扩展可以提供一些思路吗，我正在尝试增加日期点选框来进行多日期的筛选？

### ISSUE THREAD

**Issue by tongtongking** [huangshuwei/vue-easytable#337]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能**
我正在开发一个多人在线编辑功能的表格，目前遇到一些瓶颈，随着数据越来越多，需要筛选的日期也越来越多，这时候再通过原来的多选进行筛时间就会有问题，但是又不清楚怎么把时间筛选集成进去？

**描述下，你希望得到的什么解决方案 **
我想通过操作filterMethod(filters)中的filters的值达到我的目的，但是我只能将自定义的参数通过调用filterMethod传入，而无法获取页面其他筛选项的filters的内容，导致新添加的功能完全是独立的，不能与其他字段的filters合并到一起

**是否有不错的替代方案**
我看了其他的一些表格，好像也没有类似弹出时间框的方式进行筛选，不知道有没有类似的table组件可供参考？

**Comment by huangshuwei** [comment]
The new version has solved this problem.  Use cell custom content.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
