### ISSUE TITLE
cell-merge 表格隔行单元格合并出现列丢失

### ISSUE THREAD

**Issue by lkkeep** [huangshuwei/vue-easytable#343]
需求： 实现隔行合并单元格功能。
问题：发现并没有遍历所有的列，比如总共有六列数据，进到cellMerge方法里只有四列数据，会丢失其中两列数据。
请问是什么问题呢？

**Comment by huangshuwei** [comment]
是不是有固定列，跨固定列无法合并

**Comment by lkkeep** [comment]
看了一下body-cell-merge-mixin.js的setSkipRenderCells实现，是把列给合并掉了 if (rowSpan && rowSpan > 1) {endPosY = rowIndex + rowSpan - 1; }  这里rowIndex 是不是应该改成startPosY

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
