### ISSUE TITLE
如何通过数据选中table中的某一行。而不是人工去点击row（row-click回调）

### ISSUE THREAD

**Issue by xsdream** [huangshuwei/vue-easytable#345]
你好，作者。
row-click 是某一行的单击回调方法，点击行的时候table那一行会有选中效果。但是怎样在不点击那一行的情况下，通过哪一行的数据实现行的选中效果呢？
element-table是可以做到的，请问有api提供吗。

**Comment by huangshuwei** [comment]
Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
