### ISSUE TITLE
样式设置目前无法支持鼠标滑过列样式设置

### ISSUE THREAD

**Issue by lifuyao** [huangshuwei/vue-easytable#346]
**如果鼠标放在某个单元格上，表格的行和列则出现对应的高亮颜色，目前鼠标事件，只能获取到对应的行号，获取不了对应的列号，所以没有办法实现该效果，希望各位大佬能给点建议，万分感谢**
![image](https://user-images.githubusercontent.com/21291355/100200464-9d156b00-2f39-11eb-9bf7-a6813fb3a0f9.png)

**Comment by huangshuwei** [comment]
Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
