### ISSUE TITLE
使用表格的：width="××"的属性给表格定宽度时，在列多的情况下，底部横向滚动条会盖住最后一条数据

### ISSUE THREAD

**Issue by cuimaomao0123** [huangshuwei/vue-easytable#347]
使用表格的：width="××"的属性给表格定宽度时，在列多的情况下，底部横向滚动条会盖住最后一条数据

**Comment by zhangwanqin357** [comment]
可以把滚动条宽度设窄一点的🙂

**Comment by huangshuwei** [comment]
Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)

**Comment by huangshuwei** [comment]
The new version solves this problem
