### ISSUE TITLE
高度有问题，复制到项目达不到demo的效果，代码一模一样。

### ISSUE THREAD

**Issue by apgk** [huangshuwei/vue-easytable#348]
除了设置高度，还有宽度
1.本来想设置宽度自适应，列加入宽度和自适应，最后首页直接占用1000px的宽度，直接把别的列挤没了
2.手动去除v-table-header-inner 的宽度，也不行
3.列宽度全部显示后，跟数据列宽度不对等
4.纵向滚动条很有问题，一直缺了一部分。没法显示全。
5.父级div已经设置高度90%了，最后table还是会超出一大堆，怎么设置都不起效。

**Comment by huangshuwei** [comment]
Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)

**Comment by huangshuwei** [comment]
The new version has solved this problem.
