### ISSUE TITLE
一个小bug!

### ISSUE THREAD

**Issue by Zzeo** [huangshuwei/vue-easytable#36]
![image](https://user-images.githubusercontent.com/26971142/32363624-39888eaa-c0ab-11e7-8307-b871801aee0f.png)
表格是隔行变色的, 鼠标悬停颜色变化! 但是当连续几条空数据时,鼠标悬停的效果如下:
![image](https://user-images.githubusercontent.com/26971142/32363678-6dea19a2-c0ab-11e7-9fe9-3b1108cc237c.png)

**Comment by huangshuwei** [comment]
我试了下不会啊，看我写的测试：
https://jsfiddle.net/huangsw/d6caqzw3/

你各行变色用的是内置的api吗，还是自己实现的？

**Comment by Zzeo** [comment]
是用的内置api, 有一条用于渲染表格的数据data, 然后在mounted里面对数据二次加工,(push两条空数据之后), 就会出现那样的问题
![image](https://user-images.githubusercontent.com/26971142/32365847-86d964e4-c0b6-11e7-899c-6026f46eb347.png)

**Comment by huangshuwei** [comment]
给数组对象通过push添加新属性会破坏对象的响应式
参考这里：
https://vuefe.cn/v2/api/#Vue-set

要么通过这种方式也可以
`
this.data = [...]
`

**Comment by huangshuwei** [comment]
我还是不太喜欢官方推荐的`this.$set`方式，但是有些情况下必须那么做。像你这个问题你可以通过对象赋值的方式做。看这个：
https://jsfiddle.net/huangsw/d6caqzw3/1/

**Comment by huangshuwei** [comment]
问题解决了没，先关掉了，有问题再反馈
