### ISSUE TITLE
componentName用法问题

### ISSUE THREAD

**Issue by minefo** [huangshuwei/vue-easytable#37]
>列配置 {field: 'test', title: 'test标题',width: 300, titleAlign: 'center',columnAlign:'center',componentName:'table-test',isEdit:false,isResize:true},

```
Vue.component('table-test',{
        template:`<div><el-select v-model="test" style="width: 280px" filterable  placeholder="请选择">
                        <el-option
                                v-for="item in testList"
                                :key="item.value"
                                :label="item.label"
                                :value="item.value">
                        </el-option>
                    </el-select></div>`,
        props:{
            rowData:{
                type:Object
            },
            field:{
                type:String
            },
            index:{
                type:Number
            }
        },
        data(){
           return {
               test:"",
               testList:[
                    { value: 1, label: '借记卡'},
                    { value: 2, label: '信用卡'},
               ],
           }
        }
    })  
```
发现问题，el-select是element组件，当数据改变时，el-select显示内容混乱，比如我删除一行，发现其中一行显示是删除行中的el-select

**Comment by huangshuwei** [comment]
element 组件哪个版本，我来测试下

**Comment by chenxvhua** [comment]
vue-easytable@1.5.1

**Comment by huangshuwei** [comment]
是个bug，原因是select 组件数据和table 数据脱离，即没有建立关系，导致数据删除或添加都会导致响应式失效。这个我要好好想想了

**Comment by chenxvhua** [comment]
@huangshuwei 有个建议，当表格响应数据改变重新渲染时，能不能让componentName指向的组件也重新渲染，这样可以在自定义组件里面做补救

**Comment by huangshuwei** [comment]
> @huangshuwei 有个建议，当表格响应数据改变重新渲染时，能不能让componentName指向的组件也重新渲染，这样可以在自定义组件里面做补救

可以在子组件里通过watch 监控父组件数据变化，看这里
https://jsfiddle.net/huangsw/hcdsgrgf/

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
