### ISSUE TITLE
删除某一行怎么做

### ISSUE THREAD

**Issue by alexxuan** [huangshuwei/vue-easytable#38]
![image](https://user-images.githubusercontent.com/25173149/32527631-040eaa76-c46a-11e7-8387-741a27aeb4bd.png) 想要删除某一行怎么做啊

**Comment by alexxuan** [comment]
https://jsfiddle.net/huangsw/hcdsgrgf/1/    已经知道怎么做了 3Q @huangshuwei

**Comment by huangshuwei** [comment]
> https://jsfiddle.net/huangsw/hcdsgrgf/1/ 已经知道怎么做了

这个实例是在父组件内操作删除行的，并不是在子组件内删除。
如果你用了状态管理（ vuex） 可以通过，可以通过vuex 机制去处理。

如果没有用状态管理，那么我会添加一个子组件与父组件通讯的功能，预计今天发布

**Comment by alexxuan** [comment]
嗯 麻烦了 想来想去还是子组件与父组件通讯最好了

**Comment by huangshuwei** [comment]
已实现，已发布
https://github.com/huangshuwei/vue-easytable/releases/tag/1.5.4

实例参考：
http://doc.huangsw.com/vue-easytable/app.html#/table?anchor=table-custom-columns

**Comment by yichangle** [comment]
这个功能好！我被迫用vuex，结果导致代码维护困难。

**Comment by huangshuwei** [comment]
@yichangle 
中大型项目还是需要使用状态管理器的，否则更难维护😂

**Comment by huangshuwei** [comment]
@yichangle 
> 这个功能好！我被迫用vuex，结果导致代码维护困难。

感谢一直支持，铁杆粉丝啊
