### ISSUE TITLE
级联对象显示

### ISSUE THREAD

**Issue by hujunhain** [huangshuwei/vue-easytable#43]
你好，可否实现  级联对象显示 如：  {field: 'aa.bb.cc',.....}

**Comment by huangshuwei** [comment]
> 你好，可否实现 级联对象显示 如： {field: 'aa.bb.cc',.....}

可以啊，只不过不能放到 `data(){return{}}` 里，因为这里无法获取到上下文。
猜测你的业务场景是需要动态创建`columns`信息，那么你可以把拼接`columns`对象的逻辑放到 `methods`中

**Comment by hujunhain** [comment]
不是动态columns，只是数据单元格对象里面还包含对象。只是觉得放到methods中，有编辑就要两次拼接，稍显麻烦。

**Comment by huangshuwei** [comment]
放到data 里不行的，这是vuejs 的限制

**Comment by hujunhain** [comment]
好的

**Comment by hujunhain** [comment]
在获取值的时候由:item[colField] 改为如下方法可以应付我目前的状况
getItemValue(item,colField){
                let value = item
                let colArr=colField.split(".");
                for(let i=0;i<colArr.length;i++){
                    value = value[colArr[i]]
                    if(!value) return;
                }
                return value
            },
