### ISSUE TITLE
移动端支持

### ISSUE THREAD

**Issue by tanyewei** [huangshuwei/vue-easytable#44]
有没考虑移动端支持？ 试用了下，很赞!

**Comment by huangshuwei** [comment]
目前是只支持pc 端，移动端我觉得表格应用的场景都比较简单，直接 `v-for`出来。😁

**Comment by huangshuwei** [comment]
先关闭了，移动端未来可能也不会支持，如果真做移动端table ，要舍弃一些功能，或者按照功能按需加载，否则打包后有点大
