### ISSUE TITLE
想问一下为什么import css文件后为什么会说找不到

### ISSUE THREAD

**Issue by z1047549075** [huangshuwei/vue-easytable#47]
These relative modules were not found:

* ../font/fontello.eot?58619503 in ./node_modules/css-loader?{"sourceMap":false}
!./node_modules/postcss-loader/lib?{"sourceMap":false}!./node_modules/vue-easyta
ble/libs/themes-base/index.css
* ../font/fontello.svg?58619503 in ./node_modules/css-loader?{"sourceMap":false}
!./node_modules/postcss-loader/lib?{"sourceMap":false}!./node_modules/vue-easyta
ble/libs/themes-base/index.css
* ../font/fontello.ttf?58619503 in ./node_modules/css-loader?{"sourceMap":false}
!./node_modules/postcss-loader/lib?{"sourceMap":false}!./node_modules/vue-easyta
ble/libs/themes-base/index.css
* ../font/fontello.woff2?58619503 in ./node_modules/css-loader?{"sourceMap":fals
e}!./node_modules/postcss-loader/lib?{"sourceMap":false}!./node_modules/vue-easy
table/libs/themes-base/index.css
* ../font/fontello.woff?58619503 in ./node_modules/css-loader?{"sourceMap":false
}!./node_modules/postcss-loader/lib?{"sourceMap":false}!./node_modules/vue-easyt
able/libs/themes-base/index.css
就是报这些错误，找了很久没找到原因

**Comment by huangshuwei** [comment]
你用的哪个版本？

我这边用了版本是 [1.5.8](https://github.com/huangshuwei/vue-easytable/releases/tag/1.5.8) 测试 没问题。

看你的报错信息应该是‘字体’loader 沒找到，字体loader配置可以参考：

```
  {
            test: /\.(eot|woff|woff2|ttf|svg)(\?\S*)?$/,
            use: [{
                loader: 'url-loader',
                options: {
                    limit: 5000,
                    name: 'font/[name]-[hash:8].[ext]'
                }
            }]

        }
```

有问题再反馈

**Comment by qcdys** [comment]
![image](https://user-images.githubusercontent.com/15402976/33160160-dadd4cc4-d054-11e7-9936-ca2b34e59819.png)

**Comment by huangshuwei** [comment]
@qcdys 
麻烦告诉我是哪个版本

**Comment by z1047549075** [comment]
我的也是1.5.8版本的，昨天又调试了很久没找到原因，应该是和vue-vli、node的版本有些关系，我换成是直接引用umd/css/index.css就可以了

**Comment by huangshuwei** [comment]
你的 webpack loader 配置发出来我看下

**Comment by z1047549075** [comment]
![image](https://user-images.githubusercontent.com/33889541/33160718-8eb8835e-d059-11e7-848e-49f7f1e2a298.png)
采取的是vue-cli新建项目默认的loader

**Comment by huangshuwei** [comment]
@z1047549075 
知道了，你少配置了一种字体格式：woff
你加上去应该就可以了
```
  {
            test: /\.(eot|woff|woff2|ttf|svg)(\?\S*)?$/,
            use: [{
                loader: 'url-loader',
                options: {
                    limit: 5000,
                    name: 'font/[name]-[hash:8].[ext]'
                }
            }]

        }
```

**Comment by z1047549075** [comment]
不是呢，我现在重
新换了你给的配置，然后重新run了，还是报错，去掉css就可以，或者是换成是umd/css/index.css

**Comment by huangshuwei** [comment]
woff 类型字体是必须配置的，因为table组件依赖这个字体。

配置改完以后，需要重新执行webpack 命令，你在重新打包试试

**Comment by huangshuwei** [comment]
@ALL
已修复，已发布
https://github.com/huangshuwei/vue-easytable/releases/tag/1.5.11
