### ISSUE TITLE
可不可以提供一个修改单条数据的方法

### ISSUE THREAD

**Issue by qcdys** [huangshuwei/vue-easytable#49]
比如tableData里面某一个对象发生了变化后、可以调用某个方法在table里面把这个对象及时更新掉

**Comment by huangshuwei** [comment]
`tableData` 是响应式的，修改后会立即看到dom改变。

修改某一条数据使用 `this.$set()` 参考 vue 官网：https://vuefe.cn/v2/api/#Vue-set

**Comment by qcdys** [comment]
@huangshuwei 好的、谢谢

**Comment by huangshuwei** [comment]
@qcdys 
你也有这个问题？https://github.com/huangshuwei/vue-easytable/issues/47

刚才我可能不小心把你的评论删掉了
