### ISSUE TITLE
rowSpan colSpan

### ISSUE THREAD

**Issue by PanJiaChen** [huangshuwei/vue-easytable#5]
个人建议：感觉目前实现的功能其实是大同小异的(element的table都满足)，并不解决目前任何痛点，我觉得楼主能实现rowSpan colSpan的话，会有更多人使用该组件
相关：https://github.com/ElemeFE/element/issues/670

**Comment by huangshuwei** [comment]
裤衩大神说的没毛病，看了你的很多篇博客很赞👍

话说回来，我认为table 组件最主要的是固定列、固定表头以及自适应。其他的功能往上面累加就行了。
像  element table 以及 ant table 真的很不错。我是希望后面能做出一个强大的table 组件，满足更多的业务场景。

总之感谢提出那么宝贵的建议😊

**Comment by jinfang134** [comment]
element组件性能不行，而且，自适应方面很差，在手机上会有header 与body不对齐的问题。

**Comment by huangshuwei** [comment]
@PanJiaChen 
编辑功能已经加上了，下载最新就可以使用了。看下满意不😊：
http://doc.huangsw.com/vue-easytable/app.html#/table?anchor=table-cell-merge
