### ISSUE TITLE
表头固定

### ISSUE THREAD

**Issue by eugenelyj** [huangshuwei/vue-easytable#55]
表头固定的时候需要设置height属性，我发现height设置如果超过屏幕的高度时，滑动时将不再固定表头。那么如果表格本身是占据整个屏幕的，这个height需要如何设置呢？考虑到每个设备的height不一样。

**Comment by eugenelyj** [comment]
我想到了一个解决办法，在height属性传入变量，变量设置为window.innerHeight，这样就可以解决这个问题了。

**Comment by huangshuwei** [comment]
你可能需要使用纵向自适应。
启用纵向自适应，不需要设置表格高度就可以固定表头，并且表格的高度将会在一屏内显示。
具体看api

**Comment by huangshuwei** [comment]
如果纵向自适应下方需要留出一部分高度，可以设置纵向自适应偏移量，比如表格下方有分页时。具体看api
