### ISSUE TITLE
我也出现了#47   #50相同的问题

### ISSUE THREAD

**Issue by 978740431** [huangshuwei/vue-easytable#56]
![1](https://user-images.githubusercontent.com/11803404/33270689-db179442-d3bf-11e7-801e-2d8e1e15adbf.png)
![2](https://user-images.githubusercontent.com/11803404/33270688-db15c1f8-d3bf-11e7-95ab-af35b105101d.png)
![3](https://user-images.githubusercontent.com/11803404/33270695-e0498c72-d3bf-11e7-82fc-d9200f053ae2.png)

**Comment by 978740431** [comment]
![4](https://user-images.githubusercontent.com/11803404/33270806-3ffb71b2-d3c0-11e7-9c90-5feadae219c9.png)

**Comment by ermaoL** [comment]
我也遇到这个问题了。
vue init webpack myProject，再install vue-easytable去安装，然后引入css报错。
也是直接页面引入解决的

**Comment by huangshuwei** [comment]
我现在用vue-cli 试下

**Comment by huangshuwei** [comment]
刚才我用vue-cli 没有重现，可以正常展示
node 6.10.0
npm 4.4.1
webpack 2.6.1

@978740431 @ermaoL 
提供下 npm 的版本

**Comment by ermaoL** [comment]
node 8.6.0
npm 5.5.1
webpack 3.8.1

**Comment by huangshuwei** [comment]
最终发现用最新版的 vue-cli 会出现这个问题，正在紧急修复

**Comment by huangshuwei** [comment]
@all
已修复，已发布
https://github.com/huangshuwei/vue-easytable/releases/tag/1.5.11

**Comment by ermaoL** [comment]
感谢大佬

**Comment by huangshuwei** [comment]
不客气，有问题再反馈

**Comment by vercha** [comment]
我引入css后还是报同样错，node8.9.1 ；是引用了1.5.11及以上版本就没有问题么？
