### ISSUE TITLE
表头高度设置问题

### ISSUE THREAD

**Issue by Johnson-huang** [huangshuwei/vue-easytable#59]
简单表头没试过。

复杂表头给title-rows使用titleCellClassName设置height，没有生效（字体、背景色有效）
直接用css覆盖v-table-title-cell的样式，表格下方会出现一个白条。

**Comment by huangshuwei** [comment]
简单表头和复杂表头的表头行高都是通过 `title-row-height` 设置，如果不设置则是默认值。
通过样式控制高度不会生效

**Comment by Johnson-huang** [comment]
3Q，还有个问题请教一下
我以前用的1.3.6的版本，表头可以用isResize来用鼠标来拖拽宽度，升级到1.5.11后就不行了

**Comment by huangshuwei** [comment]
因为后来有人说默认开启这个功能不好，鼠标浮动上去碍眼😂，建议关闭。后来改成可配置的了。
在这个版本改成配置形式的了https://github.com/huangshuwei/vue-easytable/releases/tag/1.5.5

**Comment by huangshuwei** [comment]
先关闭了，有问题再反馈
