### ISSUE TITLE
是否可以加一个Checkbox，radio 选择的支持？

### ISSUE THREAD

**Issue by tenbamboo** [huangshuwei/vue-easytable#6]
RT

**Comment by huangshuwei** [comment]
近期加上去

**Comment by huangshuwei** [comment]
已支持 checkbox 多选功能。

已发布
https://github.com/huangshuwei/vue-easytable/releases/tag/1.3.2

具体实例参考
http://doc.huangsw.com/vue-easytable/app.html#/table?anchor=table-selection-advanced
