### ISSUE TITLE
合并单元格情况下如果数据发生变动，可能会出现显示异常的bug，麻烦看一下

### ISSUE THREAD

**Issue by rainslytherin** [huangshuwei/vue-easytable#60]
![image](https://user-images.githubusercontent.com/13402323/33412344-9f5d43ea-d5c5-11e7-9746-10753b2aab93.png)

动态的去掉某一行数据后：(去掉的是第二行）
![image](https://user-images.githubusercontent.com/13402323/33412395-fe7cb770-d5c5-11e7-9468-5dcc22200ca2.png)

**Comment by huangshuwei** [comment]
好的，我正在看

**Comment by huangshuwei** [comment]
是个bug，正在想办法解决

**Comment by huangshuwei** [comment]
已修复，已发布
https://github.com/huangshuwei/vue-easytable/releases/tag/1.6.0

**Comment by huangshuwei** [comment]
实例参考
https://jsfiddle.net/fhfhcfk2/

**Comment by huangshuwei** [comment]
先关了，有问题再反馈

**Comment by rainslytherin** [comment]
你好，我还是遇到了类似的问题：
![image](https://user-images.githubusercontent.com/13402323/34160496-29808e82-e508-11e7-8570-a7237ea58c65.png)

我看了一下html，其中的某些行在聚合后，无故丢失了一些row，比如正常是有7列，动态更新后，就少了几列。
![image](https://user-images.githubusercontent.com/13402323/34160672-d2074410-e508-11e7-9d76-aed4132a2865.png)



但是问题却不是一直出现的，但一旦出现了后去掉其中的某些行就会一直存在类似的问题了，只要页面重新刷新就好了。

不知道是否有一个flush方法，我数据变更后，可以重新生成整个table，否则一直不好找问题。

**Comment by huangshuwei** [comment]
@rainslytherin 
希望提供一个实例，可以在这上面继续修改 https://jsfiddle.net/fhfhcfk2/ ，这样方便重现问题
