### ISSUE TITLE
没有全不选回调事件

### ISSUE THREAD

**Issue by zongpengz** [huangshuwei/vue-easytable#62]
select-all 选择所有行后是有回调数据的，但是再取消所有选择后，没有清空所有选择的数据。建议加个全不选事件

**Comment by guowangsheng** [comment]
我也遇到这个问题了，希望加个

**Comment by huangshuwei** [comment]
收到，下个版本见

**Comment by huangshuwei** [comment]
已实现，已发布
https://github.com/huangshuwei/vue-easytable/releases/tag/1.6.1

**Comment by guowangsheng** [comment]
已经更新，可以用了，谢谢

**Comment by huangshuwei** [comment]
不客气，有问题再反馈
