### ISSUE TITLE
建议添加双击行事件

### ISSUE THREAD

**Issue by Zzeo** [huangshuwei/vue-easytable#63]
正在用easytable来开发一个后台管理系统, 需求双击一个弹出框查看, 建议提供一个行的双击事件接口!

**Comment by huangshuwei** [comment]
好的，下个版本见

**Comment by huangshuwei** [comment]
已实现，已发布
https://github.com/huangshuwei/vue-easytable/releases/tag/1.6.1

**Comment by huangshuwei** [comment]
有问题再反馈，先关了
