### ISSUE TITLE
切换分页的时候，可否把单击行的样式去掉

### ISSUE THREAD

**Issue by guowangsheng** [huangshuwei/vue-easytable#64]
比如第一页选中了第一行，切换到第2页的时候第一行还有选中样式，可否去掉呢

**Comment by huangshuwei** [comment]
应该是个bug

**Comment by huangshuwei** [comment]
下个版本修复

**Comment by guowangsheng** [comment]
顺便看看 当记录只有一条的时候全不选和全选点了下面的这一条记录checkbox没任何反应

**Comment by huangshuwei** [comment]
> 顺便看看 当记录只有一条的时候全不选和全选点了下面的这一条记录checkbox没任何反应
单独开一个issue吧

**Comment by huangshuwei** [comment]
已修复，已发布
https://github.com/huangshuwei/vue-easytable/releases/tag/1.6.2

**Comment by guowangsheng** [comment]
更新后 单击行的row-click-color 这个配置无效了？单击都没背景色了

**Comment by huangshuwei** [comment]
我看下

**Comment by huangshuwei** [comment]
不会啊，你看这个实例
https://jsfiddle.net/8Lhgtknv/

你再确认下是否配置有问题

**Comment by guowangsheng** [comment]
验证了一下，发现在table 配置了row-click这个方法 就会导致这个背景色无效了

**Comment by huangshuwei** [comment]
如果在 `row-click` 事件中不去修改table 数据是不会出现这种问题的。
https://jsfiddle.net/8Lhgtknv/1/

如果修改了table 数据，会将点击记录清空。

**Comment by huangshuwei** [comment]
因为我无法判断是分页还是纯粹的数据修改，这个我再想想方案

**Comment by guowangsheng** [comment]
那我知道了，我现在单击行的时候同时做了前面的checkbox 选中的切换，这样就改变了table的数据

**Comment by huangshuwei** [comment]
倒是可以通过检测属性`paging-index`的变化来处理，但是这样就强制分页时必须传入属性`paging-index`，否则分页点击行的颜色无法去除

**Comment by huangshuwei** [comment]
不过影响也不大，因为去除点击的行样式，也只有分页这种场景。不知道你什么建议

**Comment by guowangsheng** [comment]
数据检测变化的时候，可否直接把_checked 这样的属性变化忽略掉呢

**Comment by huangshuwei** [comment]
> 数据检测变化的时候，可否直接把_checked 这样的属性变化忽略掉呢

比如只是某一行的数据变化也会导致这种问题，但这时不应该清除行点击样式

**Comment by guowangsheng** [comment]
也是的，确实只有分页才会遇到这个问题。觉得监听paging-index这个比较好点，给其再设置个默认值

**Comment by huangshuwei** [comment]
好的，一会重新发布一版

**Comment by huangshuwei** [comment]
已修复，重新发布了，再看下
https://github.com/huangshuwei/vue-easytable/releases/tag/1.6.3

**Comment by guowangsheng** [comment]
是我写错了，切换分页的时候样式还在

**Comment by guowangsheng** [comment]
可否新增一个清除选中行的方法。我是看了iview有这么一个方法clearCurrentRow，程序里面控制什么时候去操作

**Comment by huangshuwei** [comment]
是个很好的主意，下个版本加上去

**Comment by huangshuwei** [comment]
先关掉了

**Comment by huangshuwei** [comment]
已发布，已添加方法 `clearCurrentRow()`
https://github.com/huangshuwei/vue-easytable/releases/tag/1.6.4
