### ISSUE TITLE
当使用普通表头的时候，没有设置titleRows参数且数据为空数组的时候，表体高度会无限撑大

### ISSUE THREAD

**Issue by summerxiaoxiao** [huangshuwei/vue-easytable#66]
当使用普通表头的时候，没有设置titleRows参数且数据为空数组的时候，表体高度会无限撑大。
当没有数据的时候，本应显示暂无数据，但是由于表体高度无限撑大，导致下面这个div的top自动计算出错，从而在页面无法正常看到“暂无数据”。

<div class="v-table-empty-content" style="height: 50px; width: 1427px; top: 44001px;"><div class="v-table-empty-inner" style="height: 50px; width: 100%; line-height: 50px;"><a href="javascript:void(0);">暂无记录</a></div></div>

**Comment by huangshuwei** [comment]
不会啊，看这里
https://jsfiddle.net/yekabkL7/

除了表格数据为空数组，还有其他条件吗？

**Comment by summerxiaoxiao** [comment]
没有其他条件，我是因为使用复杂表头的时候没有出现这个问题，后来我就尝试普通表头也配置了titleRows参数，表格就正常了。

**Comment by huangshuwei** [comment]
普通表头不用设置`title-rows`,这个配置只有复杂表头才会用到。你看我上面的实例，确认下是不是配置有问题

**Comment by huangshuwei** [comment]
是否已解决？

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
