### ISSUE TITLE
当使用cellMerge合并行后，columns指定的formatter格式数据怎么填充到cellMerge的content上？

### ISSUE THREAD

**Issue by summerxiaoxiao** [huangshuwei/vue-easytable#67]
columns:
{"field": "xmmc","title": "项目名称",width: 400, titleAlign: 'left',columnAlign:'left',isResize:true,
                                    formatter: function (rowData,rowIndex,pagingIndex,field) {
                                        return '<a href="#">'+rowData[field]+'</a>' ;
                                    },
                                },
cellMerge:
       {
                        colSpan: 1,
                        rowSpan:1,
                        content: rowData[field],   //这里怎么获取上面columns指定formatter后的格式数据？
                        componentName: ''
                    }

**Comment by huangshuwei** [comment]
`cellMerge` 回调方法会接收到 三个参数`rowIndex,rowData,field`,你可以根据这三个参数进行拼接。无法直接从`formatter `中获取

**Comment by summerxiaoxiao** [comment]
谢谢！

**Comment by huangshuwei** [comment]
好的，有问题再反馈
