### ISSUE TITLE
列宽问题，如果我手动修改了所在容器的宽度，table不能自适应

### ISSUE THREAD

**Issue by chungkui** [huangshuwei/vue-easytable#71]
列宽问题，如果我手动修改了所在容器的宽度，table不能自适应，这个有办法解决吗

**Comment by purecreek** [comment]
![th2 3 5nl1b x_1xhk 7i](https://user-images.githubusercontent.com/29474446/34137588-bb9f1cd2-e4a6-11e7-8919-e6f6863a7d07.png)

**Comment by huangshuwei** [comment]
需要确定这几点就可以做到宽度自适应：
1、通过 is-horizontal-resize 属性设置横向自适应；
2、通过 isResize 属性设置哪些列需要自适应（所有列都可以设置，达到所有列自适应）；
3、通过 style="width:100%" 设置显示比例（百分比的值根据需求而定）；
4、每个列必须提供宽度，这个宽度是自适应的最小宽度；

**Comment by purecreek** [comment]
是按照这样写了。我做的功能是左侧菜单可以隐藏，中间内容块部分自适应剩下的宽度。就是在隐藏左侧的时候table里面的线没有自适应。我看代码好像是里面的宽度都是定值。觉得按照百分比会好

**Comment by huangshuwei** [comment]
这种情况你要在菜单隐藏的时候调用下表格强制自适应方法`resize()`

**Comment by purecreek** [comment]
嗯可以。先这样实现着。但是会导致父子组件之间耦合比较大。希望以后改进能做成响应式的。大神加油

**Comment by purecreek** [comment]
有个简单的实现方式，直接让每一列的宽度支持用户自定义为百分比的格式的就行了。现在是不支持的好像

**Comment by huangshuwei** [comment]
是的，目前列宽自适应是通过`window.resize()`方法去实现的，这一块比较复杂，目前不支持列设置百分比

**Comment by purecreek** [comment]
,mounted() {
        const that = this;
     
          window.onresize = function temp() {
            if (!that.windowResizeTimer) {
              that.windowResizeTimer = true
              setTimeout(function () {
                that.resize();
                that.windowResizeTimer = false
              }, 100)
            }

          }
    }我在你的tablle组件上加上这个钩子。然后resize的时候调用下window.onresize() 或者$(window).resize();通过这样就不用每个table写同样代码了。

**Comment by huangshuwei** [comment]
> 我在你的tablle组件上加上这个钩子。然后resize的时候调用下window.onresize() 或者$(window).resize();

我组件本身已经对 `window.onresize()`事件做了监听，只要触发了 这个时间表格会强制自适应。

其实现在是你的业务场景中会显示隐藏菜单，这时你需要强制的触发 ` window.onresize` 事件

**Comment by huangshuwei** [comment]
兼容浏览器强制触发`window.onresize()` 事件可以用这种方式：

```
function(target, type, doc, event) {
    doc = document;
    if (doc.createEvent) {
      event = doc.createEvent('HTMLEvents');
      event.initEvent(type, true, true);
      target.dispatchEvent(event);
    } else {
      event = doc.createEventObject();
      target.fireEvent('on' + type, event);
    }
  };
```


参考自：https://gist.github.com/dciccale/6226151

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
