### ISSUE TITLE
行单击回调问题

### ISSUE THREAD

**Issue by SherryZhaoHui** [huangshuwei/vue-easytable#72]
使用row-click属性，点击行后没有任何反应，使用过程需要注意什么吗？

**Comment by huangshuwei** [comment]
你看下这个实例，是不是配置有问题
https://jsfiddle.net/8Lhgtknv/1/

**Comment by SherryZhaoHui** [comment]
我也是这么写的，但是点击就是没有反应，我看页面源码里面，最外层div里有这样一个属性 row-click="function boundFn(a) {
    var l = arguments.length;
    return l
      ? l > 1
        ? fn.apply(ctx, arguments)
        : fn.call(ctx, a)
      : fn.call(ctx)
  }"，我看你给的这个实例的源码里是没有这个的，不知道是什么原因

**Comment by huangshuwei** [comment]
你用的哪个版本，最好用最新版
https://github.com/huangshuwei/vue-easytable/releases/tag/1.6.3

**Comment by SherryZhaoHui** [comment]
我原来用的是1.6.0的，更新为1.6.3就可以用了，嘿嘿，感谢

**Comment by huangshuwei** [comment]
好的，有问题再反馈
