### ISSUE TITLE
是否支持右侧列固定

### ISSUE THREAD

**Issue by Zhang-Yida** [huangshuwei/vue-easytable#76]
场景：
   最后一列为操作列，设置 fixed 属性固定到最右侧

**Comment by huangshuwei** [comment]
收到，现在还不支持

**Comment by Zhang-Yida** [comment]
awesome!

**Comment by Zhang-Yida** [comment]
请问  这个功能什么时候能开发完呢~

**Comment by huangshuwei** [comment]
可能还需要段时间，现在在开发滚动加载功能

**Comment by Zhang-Yida** [comment]
好的 谢谢

**Comment by SeanCode** [comment]
急求该功能~其他的都很棒了

**Comment by hugheschoi** [comment]
同问

**Comment by David-Tsui** [comment]
咚咚咚

**Comment by weijing1224** [comment]
请问这个功能什么时候开发完呀

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
