### ISSUE TITLE
row-dblclick事件没有响应

### ISSUE THREAD

**Issue by vcrh88** [huangshuwei/vue-easytable#77]
`<template>
    <v-table
            is-horizontal-resize
            column-width-drag
            style="width:100%"
            :columns="columns"
            :table-data="tableData"
            row-hover-color="#eee"
            row-click-color="#edf7ff"
            @row-dblclick="viewDetail"
            @row-click="viewDetail"
            @title-click="viewDetail"
            @row-mouse-leave="viewDetail"
    ></v-table>
</template>`
所有的这几个事件的都是无效

**Comment by vcrh88** [comment]
嗯，知道了，略坑啊，我还以为是个事件，原来是个属性

**Comment by huangshuwei** [comment]
是的，这个主要是因为作为属性，我可以全部放在`props`中管理。如果作为事件，零散到组件各处，不方便维护。
不好意给造成困扰了😂
