### ISSUE TITLE
固定列和缩放边栏造成表格显示异常

### ISSUE THREAD

**Issue by vcrh88** [huangshuwei/vue-easytable#78]
![image](https://user-images.githubusercontent.com/4470664/34428132-9bcf1ed0-ec84-11e7-920b-99079f888249.png)
这是侧边栏显示展开之后刷新页面，显示正常，然后收缩侧边栏，固定最左列，最左列会被拉动，跟其他列分离。

![image](https://user-images.githubusercontent.com/4470664/34428172-f8f794b6-ec84-11e7-82ca-6740ff797338.png)
这是侧边栏收缩或刷新页面，显示正常。然后展开侧边栏，固定最左列，最左列会被向右挤，跟其他列重合

**Comment by huangshuwei** [comment]
收到，尽快修复

**Comment by iTestinglab** [comment]
你好这个问题修复了没
https://github.com/huangshuwei/vue-easytable/issues/78

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
