### ISSUE TITLE
当表格配置了纵向自适应，出现横行滚动条的时候 ，横行滚动条高度会遮住最后一行表格

### ISSUE THREAD

**Issue by l1013000729** [huangshuwei/vue-easytable#79]
![image](https://user-images.githubusercontent.com/34635579/34547474-66a818ae-f136-11e7-9a8a-8bcc35a8f665.png)
如图，实际上表格高度是足够高的，最后一行的数据有点被滚动条遮住了

**Comment by huangshuwei** [comment]
收到

**Comment by snowmei** [comment]
使用表格自适应后，最后一列显示不全，v-table-body的div貌似有隐藏的margin值

**Comment by huangshuwei** [comment]
@snowmei 
能否给个实例，或者单开一个issue。谢谢

**Comment by huangshuwei** [comment]
已修复，已发布
https://github.com/huangshuwei/vue-easytable/releases/tag/1.6.5

**Comment by huangshuwei** [comment]
有问题在反馈，先关了

**Comment by cuimaomao0123** [comment]
我没有给表格设置纵向自适应，因为不希望表格内部出现滚动条，希望把滚动条放在外部容器里，但也出现了列多时，最后一行数据被滚动条压住了....
