### ISSUE TITLE
多选功能在有复杂表头时，表头没有全选的checkbox？

### ISSUE THREAD

**Issue by ricpi** [huangshuwei/vue-easytable#80]
![error](https://user-images.githubusercontent.com/5546157/34547925-8fa74826-f139-11e7-82a0-5e1cd6435d59.png)

**Comment by huangshuwei** [comment]
收到，是个bug

**Comment by ricpi** [comment]
请问这个问题预计什么时候可以修复

**Comment by huangshuwei** [comment]
最迟明天

**Comment by huangshuwei** [comment]
已发布，已修复
https://github.com/huangshuwei/vue-easytable/releases/tag/1.6.4

**Comment by huangshuwei** [comment]
不好意思，固定列下的复杂表头可以，非固定列的复杂表头没修复。这个我尽快修复

**Comment by huangshuwei** [comment]
已修复，已发布
https://github.com/huangshuwei/vue-easytable/releases/tag/1.6.6
