### ISSUE TITLE
表格的全选按钮，在左上角区域点击时，按钮位置会往左上角发生偏移

### ISSUE THREAD

**Issue by zongpengz** [huangshuwei/vue-easytable#82]
![jfgb9kngo _vn4 _c2ze](https://user-images.githubusercontent.com/22546341/34751965-7b763834-f5ea-11e7-84b4-be266e429f0c.png)
点击前；
![h2zj dlp6m7 17bag po t](https://user-images.githubusercontent.com/22546341/34751980-95ca6de0-f5ea-11e7-986b-4cba59410add.png)
在左上角点击后

**Comment by huangshuwei** [comment]
用的什么浏览器，我用chrome 和 firefox 没问题
https://jsfiddle.net/ao9a4f8v/

**Comment by zongpengz** [comment]
谷歌，你要点击左上角才出现

**Comment by huangshuwei** [comment]
重现了，感谢反馈

**Comment by huangshuwei** [comment]
已修复，已发布
https://github.com/huangshuwei/vue-easytable/releases/tag/1.6.5

**Comment by zongpengz** [comment]
辛苦了，多谢！
