### ISSUE TITLE
双击行和双击单元格

### ISSUE THREAD

**Issue by jxharp** [huangshuwei/vue-easytable#85]
非常喜欢easytabl，已经在项目中应用
能否增加双击单元格事件？ 即双击行和双击单元格只能选一。
如果能实现，希望能继续实现按列设置是否允许开启双击事件。即A列的单元格允许双击,B列不允许双击
这样的话，灵活性高点，适应的场景更多。现在似乎只能做一些展示，简单统计。

**Comment by huangshuwei** [comment]
目前支持双击行的事件 `row-dblclick` 回调参数 `{rowIndex, rowData, column}`

我觉得你的需求可以通过双击行配合回调参数实现，比如某一列不允许双击事件，可以通过回调参数 `column` 去控制

**Comment by huangshuwei** [comment]
有问题再反馈，先关了
