### ISSUE TITLE
当自定义列通过 formatter 实现时，设置了overflowTitle 无效果的问题

### ISSUE THREAD

**Issue by huangshuwei** [huangshuwei/vue-easytable#88]

**Comment by huangshuwei** [comment]
已修复，已发布
https://github.com/huangshuwei/vue-easytable/releases/tag/1.6.5

**Comment by oym0308** [comment]
![image](https://user-images.githubusercontent.com/20576931/46998369-e557e180-d154-11e8-8c55-a67ebc3a261f.png)


![image](https://user-images.githubusercontent.com/20576931/46998399-fef92900-d154-11e8-863a-8f56aa80d44d.png)
在div中title的值为空
