### ISSUE TITLE
合并单元格之后能编辑吗？

### ISSUE THREAD

**Issue by aimchina** [huangshuwei/vue-easytable#92]
单元格合并，在页面上直接编辑的时候好像不行。是不是合并和编辑不能共存啊？

**Comment by singerye** [comment]
同问

**Comment by huangshuwei** [comment]
稍等，我正在看

**Comment by huangshuwei** [comment]
看这个实例 https://jsfiddle.net/2b1qacnb/2/

合并单元格的时候是可以做编辑操作的，但是并不太好控制。因为单元格合并的时候是根据某些特征进行合并的，如行号、字段、字段的内容符合某些条件时进行合并，在这种情况下对合并后的单元格进行编辑，不能破坏合并的规则。因为所有的数据渲染都是响应式的。

**Comment by huangshuwei** [comment]
有问题再反馈，先关了
