### ISSUE TITLE
希望可以加入筛选功能,iview表格里面有。

### ISSUE THREAD

**Issue by h-wanli** [huangshuwei/vue-easytable#94]
希望加入筛选功能，像iview表格里面的筛选一样。希望easytable越来越好，以后可以用这个替代iview里面的表格，谢谢作者分享

**Comment by huangshuwei** [comment]
感谢支持，目前还不支持

**Comment by huangshuwei** [comment]
已实现，已发布
https://github.com/huangshuwei/vue-easytable/releases/tag/1.7.0
