### ISSUE TITLE
自定义表格的滚动条样式

### ISSUE THREAD

**Issue by zongpengz** [huangshuwei/vue-easytable#97]
能不能加个自定义表格滚动条样式的功能。我现在用了个第三方插件来实现自定义滚动条（解决火狐不能用css改变样式的兼容问题）；但是当用到你的表格上时，发现不好实现。
![qq 20180124162806](https://user-images.githubusercontent.com/22546341/35321975-96948e1a-0123-11e8-9225-53b517eb4135.png)

**Comment by huangshuwei** [comment]
参考这里
http://doc.huangsw.com/vue-easytable/app.html#/start

实例
https://jsfiddle.net/huangsw/nqe3qogv/

**Comment by huangshuwei** [comment]
是否已解决？
