### ISSUE TITLE
Table 组件最后一列右距中时，垂直滚动条会遮住文字

### ISSUE THREAD

**Issue by huangshuwei** [huangshuwei/vue-easytable#98]
px 的精度是整数，如果列的宽度是浮点型，会导致宽度计算不准确的问题

![11](https://user-images.githubusercontent.com/6047141/35380231-a2d91d28-01f3-11e8-9139-79389c122061.png)

**Comment by fengkuang0307** [comment]
正确的应该是这样的：
![image](https://user-images.githubusercontent.com/23735927/64403367-d77fb780-d0aa-11e9-88ff-9a69cc317e77.png)
现在是这样的：
![1](https://user-images.githubusercontent.com/23735927/64403456-33e2d700-d0ab-11e9-94ee-5355015d2254.png)

数值108881.99小数点后面的数字都显示不出来
